import { CIRCUITS_2026, DRIVERS_2026 } from "./data/game-data.mjs";

const TEAM = {
  mercedes:{name:"Mercedes",short:"MER",color:"#00d2be"}, ferrari:{name:"Ferrari",short:"FER",color:"#e8002d"}, mclaren:{name:"McLaren",short:"MCL",color:"#ff8700"},
  "red-bull":{name:"Red Bull",short:"RBR",color:"#3671c6"}, "racing-bulls":{name:"Racing Bulls",short:"RB",color:"#6692ff"}, alpine:{name:"Alpine",short:"ALP",color:"#2293d1"},
  haas:{name:"Haas",short:"HAS",color:"#b6babd"}, audi:{name:"Audi",short:"AUD",color:"#f50537"}, williams:{name:"Williams",short:"WIL",color:"#64c4ff"},
  "aston-martin":{name:"Aston Martin",short:"AMR",color:"#006f62"}, cadillac:{name:"Cadillac",short:"CAD",color:"#c9a66b"},
};
const NATIONALITY = {"Kimi Antonelli":"🇮🇹","George Russell":"🇬🇧","Lewis Hamilton":"🇬🇧","Charles Leclerc":"🇲🇨","Lando Norris":"🇬🇧","Oscar Piastri":"🇦🇺","Max Verstappen":"🇳🇱","Isack Hadjar":"🇫🇷","Liam Lawson":"🇳🇿","Arvid Lindblad":"🇬🇧","Pierre Gasly":"🇫🇷","Franco Colapinto":"🇦🇷","Oliver Bearman":"🇬🇧","Esteban Ocon":"🇫🇷","Gabriel Bortoleto":"🇧🇷","Nico Hülkenberg":"🇩🇪","Carlos Sainz":"🇪🇸","Alexander Albon":"🇹🇭","Fernando Alonso":"🇪🇸","Lance Stroll":"🇨🇦","Valtteri Bottas":"🇫🇮","Sergio Pérez":"🇲🇽"};
const POINTS=[25,18,15,12,10,8,6,4,2,1];
const SPEED_FACTOR={1:1,2:1.25,3:1.8,4:3.33,8:20};
const PIT_BASE={mercedes:2.35,ferrari:2.45,mclaren:2.32,"red-bull":2.28,"racing-bulls":2.65,alpine:2.75,haas:2.85,audi:2.70,williams:2.65,"aston-martin":2.72,cadillac:2.95};
const COMPOUNDS={MACIO:{wear:1.28,dry:1.025,wet:.62,temp:98},MÉDIO:{wear:1,dry:1,wet:.64,temp:94},DURO:{wear:.76,dry:.982,wet:.66,temp:90},INTERMEDIÁRIO:{wear:1.05,dry:.82,wet:1.02,temp:82},CHUVA:{wear:.86,dry:.68,wet:1.06,temp:72}};
const fmtTime=s=>{const n=Math.max(0,Math.ceil(s)),m=Math.floor(n/60),x=n%60;return `${String(m).padStart(2,"0")}:${String(x).padStart(2,"0")}`};
const clone=value=>JSON.parse(JSON.stringify(value));
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const rng=(seed)=>{let h=2166136261;for(const c of String(seed))h=Math.imul(h^c.charCodeAt(0),16777619);h+=0x6D2B79F5;h=Math.imul(h^(h>>>15),h|1);h^=h+Math.imul(h^(h>>>7),h|61);return((h^(h>>>14))>>>0)/4294967296};
const lapTime=n=>{const sec=Math.max(58,n);return `${Math.floor(sec/60)}:${(sec%60).toFixed(3).padStart(6,"0")}`};

function driverGrid(career,circuit){
  return DRIVERS_2026.filter(d=>d.seasonStatus==="active").map((d,index)=>({
    ...d, team:TEAM[d.teamId], controlled:career.team.drivers.some(x=>x.id===d.id), position:index+1, progress:Math.max(0,(22-index)*.002), best:null, last:null,
    tyre:100, tyreTemp:88, compound:index%3===0?"MÉDIO":"MACIO", startCompound:index%3===0?"MÉDIO":"MACIO", usedCompounds:[], engine:92, engineTemp:92, energy:100, speed:0, laps:0, inPit:false, pitRemaining:0, pitStops:0, lastPitService:null, active:false,
    paceMode:"normal", engineMode:"standard", targetCompound:index%3===0?"DURO":"MÉDIO", pitLap:Math.max(8,Math.round(circuit.laps*.42)+(index%5)), eliminated:false, score:0,
  }));
}

export function mountLiveWeekend(root, careerState, callbacks={}){
  const career=clone(careerState), circuit=career.technical.weekend.circuit||CIRCUITS_2026[0];
  const qa=new URLSearchParams(location.search).has("qa"), durationFor=phase=>qa?2:phase==="Q1"?1080:phase==="Q2"?900:phase==="Q3"?720:720;
  const rainEvent=rng(`${career.saveId}:${circuit.id}:weather`)>0.64;
  const sim={phase:"practice",segment:"TL1",practice:1,elapsed:0,duration:durationFor("TL1"),speed:1,running:false,finished:false,drivers:driverGrid(career,circuit),selectedId:career.team.drivers[0]?.id,grid:null,events:["Direção de prova: pista liberada."],lastFrame:performance.now(),lastPaint:0,q1Out:[],q2Out:[],raceStarted:false,lastEvent:0,weather:{condition:"SECO",air:24+Math.round(rng(circuit.id)*8),track:31+Math.round(rng(`${circuit.id}:track`)*12),rain:0,wet:0,forecast:rainEvent?"CHUVA PREVISTA":"ESTÁVEL"}};
  let raf=0,path=null,pathLength=1;

  const selected=()=>sim.drivers.find(d=>d.id===sim.selectedId)||sim.drivers[0];
  const sessionName=()=>sim.phase==="practice"?`TREINO LIVRE ${sim.practice}`:sim.phase==="qualifying"?sim.segment:sim.phase==="race"?"CORRIDA":"PÓDIO";
  const sessionColor=()=>sim.phase==="race"?"#e8002d":sim.phase==="qualifying"?"#b45cff":"#d9a632";
  const order=()=>sim.drivers.slice().sort((a,b)=>sim.phase==="race"?b.progress-a.progress:(a.best??999)-(b.best??999));
  const activeCount=()=>sim.segment==="Q2"?16:sim.segment==="Q3"?10:22;

  function render(){
    root.hidden=false;
    root.innerHTML=`<div class="broadcast-shell" style="--session:${sessionColor()}">
      <header class="broadcast-header"><div class="broadcast-brand"><img src="assets/media/capa-logo-horizontal.webp" alt="F1 Vale Gold Edition"><span>AO VIVO</span></div><div class="broadcast-event"><b>${circuit.flag} ${circuit.grandPrix}</b><small>ETAPA ${circuit.round||CIRCUITS_2026.findIndex(c=>c.id===circuit.id)+1} · ${circuit.name}</small></div><div class="broadcast-clock"><small>${sessionName()}</small><strong id="live-clock">${fmtTime(sim.duration)}</strong></div><button class="broadcast-exit" data-live="exit">SAIR E SALVAR</button></header>
      <div class="sponsor-ribbon"><img src="assets/official/sponsor-pirelli.webp" alt="Pirelli"><img src="assets/official/sponsor-dhl.webp" alt="DHL"><img src="assets/official/sponsor-aws.webp" alt="AWS"><img src="assets/official/sponsor-aramco.webp" alt="Aramco"><span>TRANSMISSÃO OFICIAL DA SUA EQUIPE</span></div>
      <main class="broadcast-main"><aside class="timing-tower"><div class="timing-title"><b>POS</b><span id="live-lap-label">TEMPO</span></div><div id="timing-list"></div></aside>
      <section class="track-stage"><div class="track-heading"><div><span class="live-pill">● LIVE</span><h1>${sessionName()}</h1><div class="weather-hud"><b id="weather-condition">${sim.weather.condition}</b><span id="weather-values">AR ${sim.weather.air}° · PISTA ${sim.weather.track}° · MOLHADA ${Math.round(sim.weather.wet)}%</span><small>${sim.weather.forecast}</small></div></div><div class="speed-bank">${[1,2,3,4,8].map(x=>`<button data-live="speed" data-value="${x}" class="${sim.speed===x?"is-active":""}">${x}×</button>`).join("")}<button data-live="pause">${sim.running?"PAUSAR":"INICIAR"}</button></div></div>
        <div class="track-map"><svg viewBox="0 0 1000 520" role="img" aria-label="Traçado de ${circuit.name}"><defs><filter id="track-glow"><feGaussianBlur stdDeviation="7" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path class="track-shadow" d="${circuit.trackPath}"/><path id="live-track-line" class="track-line" d="${circuit.trackPath}"/><g id="car-layer">${sim.drivers.map((d,i)=>`<g class="map-car ${d.controlled?"is-player":""}" data-car="${d.id}"><circle r="${d.controlled?11:7}" fill="${d.team.color}"/><text x="0" y="3">${i+1}</text></g>`).join("")}</g></svg><div class="race-control"><b>DIREÇÃO DE PROVA</b><span id="race-message">${sim.events[0]}</span></div></div>
        <div id="session-summary" class="session-summary" hidden></div>
      </section><aside class="pit-wall"><div class="pit-tabs"><button class="is-active">PIT WALL</button><button>TELEMETRIA</button></div><div id="driver-selector" class="driver-selector">${career.team.drivers.map(d=>`<button data-live="select-driver" data-id="${d.id}" class="${sim.selectedId===d.id?"is-active":""}"><img src="assets/official/driver-${d.name.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-")}.webp" alt="${d.name}"><span>${d.name.split(" ").pop()}</span></button>`).join("")}</div><div id="telemetry-panel"></div></aside></main>
      <footer class="broadcast-footer"><span id="phase-progress">${sessionName()}</span><div class="footer-track"><i id="phase-bar"></i></div><span>${circuit.laps} VOLTAS · ${circuit.country.toUpperCase()}</span></footer>
    </div>`;
    path=root.querySelector("#live-track-line");pathLength=path?.getTotalLength()||1;
    root.onclick=handleClick; root.oninput=handleInput;
    paint(true);
  }

  function telemetryHtml(){
    const d=selected(), setup=career.technical.setup;
    if(sim.phase==="practice")return `<section class="driver-live"><h2>${NATIONALITY[d.name]||"🏁"} ${d.name}</h2><p>${d.team.name} · ${d.active?"NA PISTA":"NOS BOXES"}</p><div class="telemetry-grid"><div><b id="tel-speed">${Math.round(d.speed)}</b><span>KM/H</span></div><div><b id="tel-tyre">${Math.round(d.tyre)}%</b><span>PNEUS</span></div><div><b id="tel-temp">${Math.round(d.engineTemp)}°</b><span>MOTOR</span></div><div><b id="tel-energy">${Math.round(d.energy)}%</b><span>ENERGIA</span></div></div><button class="pit-primary" data-live="toggle-track">${d.active?"RECOLHER AOS BOXES":"ENVIAR PARA A PISTA"}</button><h3>ACERTO EM TEMPO REAL</h3>${[["frontWing","ASA DIANTEIRA"],["rearWing","ASA TRASEIRA"],["suspension","SUSPENSÃO"],["brakeBalance","BALANÇO DE FREIO"]].map(([k,l])=>`<label class="live-range"><span>${l}<b>${setup[k]}</b></span><input data-setup="${k}" type="range" min="0" max="100" value="${setup[k]}"></label>`).join("")}</section>`;
    if(sim.phase==="qualifying")return `<section class="driver-live"><h2>${NATIONALITY[d.name]||"🏁"} ${d.name}</h2><p>${d.eliminated?"ELIMINADO":d.active?"VOLTA RÁPIDA":"NOS BOXES"}</p><div class="telemetry-grid"><div><b id="tel-speed">${Math.round(d.speed)}</b><span>KM/H</span></div><div><b id="tel-tyre">${Math.round(d.tyre)}%</b><span>PNEUS</span></div><div><b>${d.best?lapTime(d.best):"—"}</b><span>MELHOR</span></div><div><b>${d.position}</b><span>POSIÇÃO</span></div></div><button class="pit-primary" data-live="toggle-track" ${d.eliminated?"disabled":""}>${d.active?"ABORTAR VOLTA":"ENVIAR PARA VOLTA RÁPIDA"}</button><p class="strategy-note">Q1 elimina 6 pilotos, Q2 elimina mais 6 e Q3 define as dez primeiras posições.</p></section>`;
    if(sim.phase==="race")return `<section class="driver-live"><h2>${NATIONALITY[d.name]||"🏁"} ${d.name}</h2><p>P${d.position} · VOLTA ${Math.min(circuit.laps,Math.floor(d.progress)+1)}/${circuit.laps}</p><div class="telemetry-grid"><div><b id="tel-speed">${Math.round(d.speed)}</b><span>KM/H</span></div><div><b id="tel-tyre">${Math.round(d.tyre)}%</b><span>${d.compound}</span></div><div><b id="tel-temp">${Math.round(d.engineTemp)}°</b><span>MOTOR</span></div><div><b id="tel-energy">${Math.round(d.energy)}%</b><span>ENERGIA</span></div><div><b id="tel-tyre-temp">${Math.round(d.tyreTemp)}°</b><span>TEMP. PNEU</span></div><div><b id="tel-stops">${d.pitStops}/1</b><span>PARADA OBRIGATÓRIA</span></div></div><label class="control-label">RITMO<select data-strategy="paceMode"><option value="conserve" ${d.paceMode==="conserve"?"selected":""}>Poupar</option><option value="normal" ${d.paceMode==="normal"?"selected":""}>Normal</option><option value="attack" ${d.paceMode==="attack"?"selected":""}>Atacar</option></select></label><label class="control-label">MOTOR<select data-strategy="engineMode"><option value="conserve" ${d.engineMode==="conserve"?"selected":""}>Conservar</option><option value="standard" ${d.engineMode==="standard"?"selected":""}>Padrão</option><option value="push" ${d.engineMode==="push"?"selected":""}>Potência máxima</option></select></label><label class="control-label">PRÓXIMO PNEU<select data-strategy="targetCompound">${["MACIO","MÉDIO","DURO","INTERMEDIÁRIO","CHUVA"].map(c=>`<option ${d.targetCompound===c?"selected":""}>${c}</option>`).join("")}</select></label><label class="control-label">JANELA DE PIT<input data-strategy="pitLap" type="number" min="2" max="${circuit.laps-1}" value="${d.pitLap}"></label><button class="pit-primary pit-stop" data-live="pit" ${d.inPit?"disabled":""}>${d.inPit?`SERVIÇO ${d.pitRemaining.toFixed(1)}s`:"CHAMAR PARA O BOX"}</button><p class="strategy-note">Em pista seca, todos devem parar e usar dois compostos de slick. A engenharia fará chamada automática no limite da janela.</p></section>`;
    return `<section class="driver-live"><h2>Fim de semana concluído</h2><p>Resultado e troféu foram gravados no save.</p></section>`;
  }

  function paint(force=false){
    const now=performance.now();if(!force&&now-sim.lastPaint<110)return;sim.lastPaint=now;
    const sorted=order();sorted.forEach((d,i)=>d.position=i+1);
    const list=root.querySelector("#timing-list");if(list)list.innerHTML=sorted.map((d,i)=>`<button class="timing-row ${d.controlled?"is-player":""} ${d.eliminated?"is-out":""}" data-live="select-driver" data-id="${d.id}"><b>${i+1}</b><i style="--team:${d.team.color}"></i><span>${NATIONALITY[d.name]||""} ${d.name.split(" ").pop().slice(0,10)}</span><small>${sim.phase==="race"?`${Math.min(circuit.laps,Math.floor(d.progress)+1)}/${circuit.laps}`:d.best?lapTime(d.best):"NO TIME"}</small></button>`).join("");
    const lapLabel=root.querySelector("#live-lap-label");if(lapLabel)lapLabel.textContent=sim.phase==="race"?`VOLTA ${Math.min(circuit.laps,Math.floor(sorted[0]?.progress||0)+1)}/${circuit.laps}`:"TEMPO";
    const leader=sorted[0],clock=root.querySelector("#live-clock");if(clock)clock.textContent=fmtTime(sim.phase==="race"?Math.max(0,(circuit.laps-(leader?.progress||0))*circuit.lapSeconds):sim.duration-sim.elapsed);
    const bar=root.querySelector("#phase-bar");if(bar)bar.style.width=`${clamp((sim.phase==="race"?(leader?.progress||0)/circuit.laps:sim.elapsed/sim.duration)*100)}%`;
    const wc=root.querySelector("#weather-condition"),wv=root.querySelector("#weather-values");if(wc)wc.textContent=sim.weather.condition;if(wv)wv.textContent=`AR ${sim.weather.air}° · PISTA ${Math.round(sim.weather.track)}° · MOLHADA ${Math.round(sim.weather.wet)}%`;
    const panel=root.querySelector("#telemetry-panel");if(panel&&force)panel.innerHTML=telemetryHtml();else if(panel){const d=selected();const s=panel.querySelector("#tel-speed"),t=panel.querySelector("#tel-tyre"),m=panel.querySelector("#tel-temp"),e=panel.querySelector("#tel-energy");if(s)s.textContent=Math.round(d.speed);if(t)t.textContent=`${Math.round(d.tyre)}%`;if(m)m.textContent=`${Math.round(d.engineTemp)}°`;if(e)e.textContent=`${Math.round(d.energy)}%`;}
    for(const d of sim.drivers){const car=root.querySelector(`[data-car="${d.id}"]`);if(!car||d.eliminated&&sim.phase==="qualifying"){if(car)car.style.opacity=".15";continue}const point=path?.getPointAtLength(((d.progress%1)+1)%1*pathLength);if(point)car.setAttribute("transform",`translate(${point.x} ${point.y})`);car.style.opacity=d.active||sim.phase==="race"?"1":".32";}
  }

  function updateWeather(dt){if(rainEvent&&sim.phase==="race"){const lap=order()[0]?.progress||0,target=lap>circuit.laps*.28&&lap<circuit.laps*.72?72:0;sim.weather.rain+=Math.sign(target-sim.weather.rain)*Math.min(Math.abs(target-sim.weather.rain),dt*1.1)}sim.weather.wet=clamp(sim.weather.wet+(sim.weather.rain>8?dt*.7:-dt*.28));sim.weather.track=clamp(sim.weather.track+(sim.weather.rain>10?-dt*.03:dt*.008),18,48);sim.weather.condition=sim.weather.rain>48?"CHUVA FORTE":sim.weather.rain>8?"CHUVA":sim.weather.wet>18?"PISTA ÚMIDA":"SECO"}
  function setupFit(){const s=career.technical.setup;return clamp(100-Math.abs(s.frontWing-(circuit.aero>78?72:circuit.power>82?38:54))*.3-Math.abs(s.suspension-(circuit.tyre>75?62:48))*.2)}
  const rivalTeamRating=id=>({mercedes:92,ferrari:89,mclaren:87,"red-bull":84,"racing-bulls":73,alpine:72,haas:68,audi:67,williams:66,"aston-martin":63,cadillac:61}[id]||68);
  function practiceTick(dt){for(const d of sim.drivers){if(!d.controlled)d.active=rng(`${d.id}:${sim.practice}:${Math.floor(sim.elapsed/20)}`)>.18;if(!d.active)continue;const teamRating=d.teamId===career.team.id.replace("team-2026-","")?career.team.overall:rivalTeamRating(d.teamId),performance=(d.overall*.58+teamRating*.18+setupFit()*.24)/100,actualLap=circuit.lapSeconds*(1.085-(performance-.7)*.16);d.progress+=dt/actualLap;d.speed=175+performance*145+rng(`${d.id}:${Math.floor(sim.elapsed)}`)*18;d.tyre=clamp(d.tyre-dt/circuit.lapSeconds*(5+circuit.tyre/12));d.tyreTemp+=(COMPOUNDS[d.compound].temp-d.tyreTemp)*dt*.025;d.engineTemp=clamp(86+d.speed/20,80,122);d.energy=clamp(d.energy-dt*.018);if(Math.floor(d.progress)>d.laps){d.laps=Math.floor(d.progress);const time=actualLap*(.99+rng(`${d.id}:fp:${d.laps}`)*.025);d.last=time;d.best=Math.min(d.best??999,time)}}}
  function qualifyingTick(dt){const contenders=sim.drivers.filter(d=>!d.eliminated).slice(0,activeCount());for(const d of contenders){if(!d.controlled)d.active=rng(`${d.id}:${sim.segment}:${Math.floor(sim.elapsed/22)}`)>.12;if(!d.active)continue;const teamRating=d.teamId===career.team.id.replace("team-2026-","")?career.team.overall:rivalTeamRating(d.teamId),performance=(d.overall*.68+teamRating*.22+setupFit()*.10)/100,actualLap=circuit.lapSeconds*(1.045-(performance-.7)*.13);d.progress+=dt/actualLap;d.speed=205+performance*128;d.tyre=clamp(d.tyre-dt/circuit.lapSeconds*9);if(Math.floor(d.progress)>d.laps){d.laps=Math.floor(d.progress);const time=actualLap*(.992+rng(`${d.id}:${sim.segment}:${d.laps}`)*.018);d.best=Math.min(d.best??999,time)}}}
  function compoundGrip(d){const wet=sim.weather.wet,c=COMPOUNDS[d.compound]||COMPOUNDS.MÉDIO;if(wet>55)return c.wet;if(wet>18)return d.compound==="INTERMEDIÁRIO"?1.03:d.compound==="CHUVA"?.94:c.dry*(1-wet/180);return c.dry}
  function raceTick(dt){updateWeather(dt);for(const d of sim.drivers){d.active=true;if(d.inPit){d.pitRemaining-=dt;d.speed=80;if(d.pitRemaining<=0){d.inPit=false;d.tyre=100;d.compound=d.targetCompound;d.usedCompounds.push(d.compound);sim.events.unshift(`${d.name}: parada ${d.lastPitService.toFixed(2)}s, pneus ${d.compound.toLowerCase()}.`)}continue}const controlled=d.controlled,paceBoost=controlled?(d.paceMode==="attack"?.035:d.paceMode==="conserve"?-.028:0):(rng(`${d.id}:mode:${Math.floor(sim.elapsed/40)}`)-.5)*.025,engineBoost=controlled?(d.engineMode==="push"?.022:d.engineMode==="conserve"?-.02:0):0,teamRating=d.teamId===career.team.id.replace("team-2026-","")?career.team.overall:rivalTeamRating(d.teamId),tyreLife=clamp(.72+d.tyre/360,.70,1),base=.88+(d.overall*.62+teamRating*.38-70)/500,step=dt/circuit.lapSeconds*base*(1+paceBoost+engineBoost)*tyreLife*compoundGrip(d);d.progress+=step;d.speed=190+base*115+(paceBoost+engineBoost)*180;const wearPerLap=(8+circuit.tyre/11)*(COMPOUNDS[d.compound]?.wear||1)*(paceBoost>0?1.22:paceBoost<0?.82:1);d.tyre=clamp(d.tyre-step*wearPerLap);d.tyreTemp+=(COMPOUNDS[d.compound].temp+(paceBoost>0?7:0)-d.tyreTemp)*dt*.04;d.engineTemp=clamp(d.engineTemp+dt*((engineBoost>.01?.11:-.025)+(d.engineTemp<99?.025:0)),82,132);d.energy=clamp(d.energy+dt*(d.paceMode==="conserve"?.16:d.paceMode==="attack"?-.18:.02));const lap=Math.floor(d.progress);if(!d.inPit&&d.pitStops===0&&(lap>=d.pitLap||lap>=circuit.laps-3||d.tyre<24))startPit(d);if(sim.weather.wet>35&&!["INTERMEDIÁRIO","CHUVA"].includes(d.compound)&&!d.inPit){d.targetCompound=sim.weather.wet>62?"CHUVA":"INTERMEDIÁRIO";startPit(d)}if(d.tyre<8)d.progress-=dt/circuit.lapSeconds*.22;if(d.engineTemp>124)d.progress-=dt/circuit.lapSeconds*.12}const leader=order()[0];if(leader&&leader.progress>=circuit.laps)finishRace();const mark=Math.floor(sim.elapsed/45);if(mark>0&&mark>sim.lastEvent){sim.lastEvent=mark;const messages=["Bandeira amarela no setor 2. Sem ultrapassagens.","Pista liberada. Bandeira verde.","DRS habilitado pela direção de prova.",rainEvent?"Radar: chuva se aproxima do circuito.":"Radar: condições estáveis.","Direção de prova confirma pista livre."];sim.events.unshift(messages[(mark-1)%messages.length]);const msg=root.querySelector("#race-message");if(msg)msg.textContent=sim.events[0]}}
  function tick(now){const raw=Math.min(.08,(now-sim.lastFrame)/1000);sim.lastFrame=now;if(sim.running&&!sim.finished){const dt=raw*(qa?(sim.phase==="race"?3000:100):SPEED_FACTOR[sim.speed]);sim.elapsed+=dt;if(sim.phase==="practice")practiceTick(dt);if(sim.phase==="qualifying")qualifyingTick(dt);if(sim.phase==="race")raceTick(dt);if(sim.phase!=="race"&&sim.elapsed>=sim.duration&&!sim.finished)finishSession();paint()}raf=requestAnimationFrame(tick)}

  function finishSession(){sim.running=false;sim.finished=true;sim.elapsed=sim.duration;if(sim.phase==="practice")finishPractice();else if(sim.phase==="qualifying")finishQualifying();else if(sim.phase==="race")finishRace();}
  function finishPractice(){const sorted=order();career.technical.weekend.practiceRuns.push({session:`TL${sim.practice}`,pace:Math.round(100-(sorted[0]?.best||80)),setup:Math.round(Object.values(career.technical.setup).reduce((a,b)=>a+b,0)/4),tyreWear:Math.round(100-(selected()?.tyre||100))});career.technical.weekend.telemetry={pace:Math.round(100-(selected()?.best||80)),setup:Math.round(Object.values(career.technical.setup).reduce((a,b)=>a+b,0)/4),tyreWear:Math.round(100-(selected()?.tyre||100)),confidence:68+sim.practice*8};showSummary(`TL${sim.practice} CONCLUÍDO`,sorted.slice(0,5),sim.practice<3?`AVANÇAR PARA TL${sim.practice+1}`:"AVANÇAR PARA CLASSIFICAÇÃO");persist(`TL${sim.practice} concluído em ${circuit.name}.`)}
  function finishQualifying(){const sorted=order().filter(d=>!d.eliminated);if(sim.segment==="Q1"){const out=sorted.slice(16);out.forEach(d=>d.eliminated=true);sim.q1Out=out;showSummary("Q1 CONCLUÍDO",sorted.slice(0,16),"AVANÇAR PARA Q2");}else if(sim.segment==="Q2"){const out=sorted.slice(10);out.forEach(d=>d.eliminated=true);sim.q2Out=out;showSummary("Q2 CONCLUÍDO",sorted.slice(0,10),"AVANÇAR PARA Q3");}else{const top=sorted.slice(0,10),grid=[...top,...sim.q2Out,...sim.q1Out];grid.forEach((d,i)=>d.position=i+1);sim.grid=grid;career.technical.weekend.qualifying=grid.map(d=>({driverId:d.id,name:d.name,teamId:d.teamId,position:d.position,bestLap:d.best}));career.technical.weekend.phase="grid-set";showSummary("GRID DE LARGADA DEFINIDO",grid.slice(0,10),"INICIAR CORRIDA");persist(`Grid completo definido para ${circuit.name}.`);}}
  function showSummary(title,drivers,button){const box=root.querySelector("#session-summary");if(!box)return;box.hidden=false;box.innerHTML=`<div class="summary-card"><p class="eyebrow">RESULTADO OFICIAL</p><h2>${title}</h2><div class="summary-results">${drivers.slice(0,10).map((d,i)=>`<span><b>P${i+1}</b><i style="--team:${d.team.color}"></i>${NATIONALITY[d.name]||""} ${d.name}<small>${d.best?lapTime(d.best):"—"}</small></span>`).join("")}</div><button class="pit-primary" data-live="next-session">${button}</button></div>`;}
  function resetDrivers(keepGrid=false){for(const [i,d] of sim.drivers.entries()){d.active=false;d.best=null;d.last=null;d.tyre=100;d.tyreTemp=88;d.energy=100;d.engineTemp=92;d.speed=0;d.laps=0;d.inPit=false;if(!keepGrid)d.progress=(22-i)*.002;}}
  function nextSession(){const box=root.querySelector("#session-summary");if(box)box.hidden=true;sim.finished=false;sim.elapsed=0;sim.running=false;if(sim.phase==="practice"&&sim.practice<3){sim.practice++;sim.segment=`TL${sim.practice}`;sim.duration=durationFor(sim.segment);resetDrivers();}else if(sim.phase==="practice"){sim.phase="qualifying";sim.segment="Q1";sim.duration=durationFor("Q1");resetDrivers();}else if(sim.phase==="qualifying"&&sim.segment==="Q1"){sim.segment="Q2";sim.duration=durationFor("Q2");resetDrivers(true);}else if(sim.phase==="qualifying"&&sim.segment==="Q2"){sim.segment="Q3";sim.duration=durationFor("Q3");resetDrivers(true);}else if(sim.phase==="qualifying"){startRace();return}render();}
  function startRace(){sim.phase="race";sim.segment="RACE";sim.duration=circuit.lapSeconds*circuit.laps;sim.elapsed=0;sim.finished=false;sim.running=false;sim.raceStarted=true;sim.lastEvent=0;const grid=sim.grid||order();sim.drivers=grid.map((d,i)=>{const compound=i<10?"MACIO":"MÉDIO";return{...d,eliminated:false,active:true,progress:(grid.length-i)*.003,position:i+1,best:null,last:null,tyre:100,tyreTemp:82,compound,startCompound:compound,usedCompounds:[compound],pitStops:0,lastPitService:null,engineTemp:91,energy:100,pitLap:Math.max(5,Math.round(circuit.laps*(i%2?.48:.39))),targetCompound:compound==="MACIO"?"MÉDIO":"DURO",inPit:false}});sim.events.unshift("Formação concluída. Parada obrigatória confirmada para todos os carros.");render();}
  function startPit(d){if(d.inPit)return;if(sim.weather.wet<18&&d.pitStops===0&&d.targetCompound===d.startCompound)d.targetCompound=d.startCompound==="MACIO"?"MÉDIO":"DURO";const crew=(d.controlled?Math.round(career.team.staff.filter(x=>x.department==="Operações"||x.department==="Corrida").reduce((a,x)=>a+x.rating,0)/Math.max(1,career.team.staff.filter(x=>x.department==="Operações"||x.department==="Corrida").length)):72),service=clamp((PIT_BASE[d.teamId]||2.8)+(72-crew)*.012+(rng(`${d.id}:pit:${d.pitStops}`)-.5)*.45,1.95,4.8);d.inPit=true;d.pitStops++;d.lastPitService=service;d.pitRemaining=(circuit.pitLoss||22)+service;sim.events.unshift(`${d.name} entra nos boxes: ${d.targetCompound.toLowerCase()}, serviço previsto ${service.toFixed(2)}s.`);}
  function finishRace(){if(sim.finished&&sim.phase==="podium")return;sim.running=false;sim.finished=true;const result=order();result.sort((a,b)=>(b.pitStops>0)-(a.pitStops>0)||b.progress-a.progress);result.forEach((d,i)=>d.position=i+1);career.technical.weekend.raceResult=result.map((d,i)=>({driverId:d.id,name:d.name,teamId:d.teamId,position:i+1,points:POINTS[i]||0,compound:d.compound,tyre:Math.round(d.tyre),pitStops:d.pitStops,pitService:d.lastPitService,ruleCompliant:d.pitStops>0}));career.technical.weekend.phase="completed";career.calendar&&(career.calendar.raceDue=false);career.championship||={drivers:{},constructors:{},rounds:[]};for(const [i,d] of result.entries()){const pts=POINTS[i]||0,dc=career.championship.drivers[d.id]||={driverId:d.id,name:d.name,teamId:d.teamId,points:0,wins:0},tc=career.championship.constructors[d.teamId]||={teamId:d.teamId,name:d.team.name,points:0,wins:0};dc.points+=pts;tc.points+=pts;if(i===0){dc.wins++;tc.wins++}}career.championship.rounds.push({round:career.technical.weekend.round+1,circuitId:circuit.id,grandPrix:circuit.grandPrix,winner:result[0].name});career.trophies||=[];career.trophies.unshift({id:`trophy-${circuit.id}-${Date.now()}`,round:career.technical.weekend.round+1,circuitId:circuit.id,grandPrix:circuit.grandPrix,country:circuit.country,flag:circuit.flag,winner:result[0].name,podium:result.slice(0,3).map(d=>({name:d.name,team:d.team.name,flag:NATIONALITY[d.name]||"🏁"}))});const teamResult=result.filter(d=>d.controlled),target=Math.max(3,Math.round(12-(career.team.overall-60)/4)),met=teamResult.some(d=>d.position<=target);career.boardConfidence=clamp(career.boardConfidence+(met?3:-5));career.manager.reputation=clamp(career.manager.reputation+(met?2:-1));career.inbox.unshift({id:`race-report-${circuit.id}`,week:career.week,day:career.calendar?.day,senderId:"camila",sector:"Direção esportiva",title:`Relatório: ${circuit.grandPrix}`,text:`Meta P${target}: ${met?"cumprida":"não cumprida"}. ${teamResult.map(d=>`${d.name} P${d.position}`).join(" e ")}. Confiança do conselho: ${career.boardConfidence}%.`,read:false});career.history.push({week:career.week,type:"race",text:`${result[0].name} venceu ${circuit.grandPrix}; ${career.team.name}: ${teamResult.map(d=>`${d.name} P${d.position}`).join(" e ")}.`});persist(`Corrida concluída: ${result[0].name} venceu.`);sim.phase="podium";renderPodium(result);}
  function renderPodium(result){cancelAnimationFrame(raf);root.innerHTML=`<section class="podium-screen"><div class="confetti-layer"></div><button class="broadcast-exit" data-live="exit">SAIR E SALVAR</button><p class="eyebrow">${circuit.flag} ${circuit.grandPrix.toUpperCase()}</p><h1>PÓDIO</h1><div class="podium-stage"><article class="podium-place second"><span>🥈</span><img src="assets/official/driver-${slug(result[1].name)}.webp" alt="${result[1].name}"><h2>${NATIONALITY[result[1].name]} ${result[1].name}</h2><b>${result[1].team.name}</b><i>2</i></article><article class="podium-place first"><span>🏆</span><img src="assets/official/driver-${slug(result[0].name)}.webp" alt="${result[0].name}"><h2>${NATIONALITY[result[0].name]} ${result[0].name}</h2><b>${result[0].team.name}</b><i>1</i></article><article class="podium-place third"><span>🥉</span><img src="assets/official/driver-${slug(result[2].name)}.webp" alt="${result[2].name}"><h2>${NATIONALITY[result[2].name]} ${result[2].name}</h2><b>${result[2].team.name}</b><i>3</i></article></div><div class="podium-actions"><button class="pit-primary" data-live="exit">VOLTAR AO PADDOCK</button></div></section>`;root.onclick=handleClick;}
  function slug(v){return v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-")}
  function persist(message){career.updatedAt=new Date().toISOString();callbacks.onSave?.(clone(career),message)}
  function exitLive(){cancelAnimationFrame(raf);persist("Fim de semana salvo.");root.hidden=true;root.innerHTML="";callbacks.onExit?.(clone(career));}
  function handleInput(e){const d=selected();if(e.target.dataset.setup){career.technical.setup[e.target.dataset.setup]=Number(e.target.value);e.target.previousElementSibling.querySelector("b").textContent=e.target.value;persist("Acerto atualizado durante a sessão.")}if(e.target.dataset.strategy){d[e.target.dataset.strategy]=e.target.type==="number"?Number(e.target.value):e.target.value;}}
  function handleClick(e){const b=e.target.closest("[data-live]");if(!b)return;const action=b.dataset.live;if(action==="exit")exitLive();if(action==="speed"){sim.speed=Number(b.dataset.value);root.querySelectorAll('[data-live="speed"]').forEach(x=>x.classList.toggle("is-active",x===b));}if(action==="pause"){sim.running=!sim.running;b.textContent=sim.running?"PAUSAR":"CONTINUAR";}if(action==="select-driver"){sim.selectedId=b.dataset.id;root.querySelectorAll('[data-live="select-driver"]').forEach(x=>x.classList.toggle("is-active",x.dataset.id===sim.selectedId));const p=root.querySelector("#telemetry-panel");if(p)p.innerHTML=telemetryHtml();}if(action==="toggle-track"){const d=selected();d.active=!d.active;b.textContent=d.active?"RECOLHER AOS BOXES":"ENVIAR PARA A PISTA";}if(action==="next-session")nextSession();if(action==="pit")startPit(selected());}
  render();raf=requestAnimationFrame(tick);
  return {destroy(){cancelAnimationFrame(raf);root.hidden=true;root.innerHTML=""}};
}
