import { CIRCUITS_2026, DRIVERS_2026 } from "./data/game-data.mjs";

const TEAM = {
  mercedes:{name:"Mercedes",short:"MER",color:"#00d2be"}, ferrari:{name:"Ferrari",short:"FER",color:"#e8002d"}, mclaren:{name:"McLaren",short:"MCL",color:"#ff8700"},
  "red-bull":{name:"Red Bull",short:"RBR",color:"#3671c6"}, "racing-bulls":{name:"Racing Bulls",short:"RB",color:"#6692ff"}, alpine:{name:"Alpine",short:"ALP",color:"#2293d1"},
  haas:{name:"Haas",short:"HAS",color:"#b6babd"}, audi:{name:"Audi",short:"AUD",color:"#f50537"}, williams:{name:"Williams",short:"WIL",color:"#64c4ff"},
  "aston-martin":{name:"Aston Martin",short:"AMR",color:"#006f62"}, cadillac:{name:"Cadillac",short:"CAD",color:"#c9a66b"},
};
const NATIONALITY = {"Kimi Antonelli":"🇮🇹","George Russell":"🇬🇧","Lewis Hamilton":"🇬🇧","Charles Leclerc":"🇲🇨","Lando Norris":"🇬🇧","Oscar Piastri":"🇦🇺","Max Verstappen":"🇳🇱","Isack Hadjar":"🇫🇷","Liam Lawson":"🇳🇿","Arvid Lindblad":"🇬🇧","Pierre Gasly":"🇫🇷","Franco Colapinto":"🇦🇷","Oliver Bearman":"🇬🇧","Esteban Ocon":"🇫🇷","Gabriel Bortoleto":"🇧🇷","Nico Hülkenberg":"🇩🇪","Carlos Sainz":"🇪🇸","Alexander Albon":"🇹🇭","Fernando Alonso":"🇪🇸","Lance Stroll":"🇨🇦","Valtteri Bottas":"🇫🇮","Sergio Pérez":"🇲🇽"};
const POINTS=[25,18,15,12,10,8,6,4,2,1];
const fmtTime=s=>{const n=Math.max(0,Math.ceil(s*60)),m=Math.floor(n/60),x=n%60;return `${String(m).padStart(2,"0")}:${String(x).padStart(2,"0")}`};
const clone=value=>JSON.parse(JSON.stringify(value));
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const rng=(seed)=>{let h=2166136261;for(const c of String(seed))h=Math.imul(h^c.charCodeAt(0),16777619);h+=0x6D2B79F5;h=Math.imul(h^(h>>>15),h|1);h^=h+Math.imul(h^(h>>>7),h|61);return((h^(h>>>14))>>>0)/4294967296};
const lapTime=n=>{const sec=Math.max(58,n);return `${Math.floor(sec/60)}:${(sec%60).toFixed(3).padStart(6,"0")}`};

function driverGrid(career,circuit){
  return DRIVERS_2026.filter(d=>d.seasonStatus==="active").map((d,index)=>({
    ...d, team:TEAM[d.teamId], controlled:career.team.drivers.some(x=>x.id===d.id), position:index+1, progress:Math.max(0,(22-index)*.002), best:null, last:null,
    tyre:100, compound:index%3===0?"MÉDIO":"MACIO", engine:92, engineTemp:92, energy:100, speed:0, laps:0, inPit:false, pitRemaining:0, active:false,
    paceMode:"normal", engineMode:"standard", targetCompound:"MÉDIO", pitLap:Math.max(8,Math.round(circuit.laps*.42)+(index%5)), eliminated:false, score:0,
  }));
}

export function mountLiveWeekend(root, careerState, callbacks={}){
  const career=clone(careerState), circuit=career.technical.weekend.circuit||CIRCUITS_2026[0];
  const sim={phase:"practice",segment:"TL1",practice:1,elapsed:0,duration:18,speed:1,running:false,finished:false,drivers:driverGrid(career,circuit),selectedId:career.team.drivers[0]?.id,grid:null,events:["Direção de prova: pista liberada."],lastFrame:performance.now(),lastPaint:0,q1Out:[],q2Out:[],raceStarted:false};
  let raf=0,path=null,pathLength=1;

  const selected=()=>sim.drivers.find(d=>d.id===sim.selectedId)||sim.drivers[0];
  const sessionName=()=>sim.phase==="practice"?`TREINO LIVRE ${sim.practice}`:sim.phase==="qualifying"?sim.segment:sim.phase==="race"?"CORRIDA":"PÓDIO";
  const sessionColor=()=>sim.phase==="race"?"#e8002d":sim.phase==="qualifying"?"#b45cff":"#d9a632";
  const order=()=>sim.drivers.slice().sort((a,b)=>sim.phase==="race"?b.progress-a.progress:(a.best??999)-(b.best??999));
  const activeCount=()=>sim.segment==="Q2"?16:sim.segment==="Q3"?10:22;

  function render(){
    root.hidden=false;
    root.innerHTML=`<div class="broadcast-shell" style="--session:${sessionColor()}">
      <header class="broadcast-header"><div class="broadcast-brand"><img src="assets/media/capa-logo-horizontal.webp" alt="F1 Vale Gold Edition"><span>AO VIVO</span></div><div class="broadcast-event"><b>${circuit.flag} ${circuit.grandPrix}</b><small>ETAPA ${circuit.round||CIRCUITS_2026.findIndex(c=>c.id===circuit.id)+1} · ${circuit.name}</small></div><div class="broadcast-clock"><small>${sessionName()}</small><strong id="live-clock">${fmtTime(sim.duration)}</strong></div><button class="broadcast-exit" data-live="exit">SAIR E SALVAR</button></header>
      <div class="sponsor-ribbon"><img src="assets/official/sponsor-pirelli.webp" alt="Pirelli"><img src="assets/official/sponsor-dhl.webp" alt="DHL"><img src="assets/official/sponsor-aws.webp" alt="AWS"><img src="assets/official/sponsor-aramco.webp" alt="Aramco"><span>TRANSMISSÃO OFICIAL DA SUA EQUIPE</span></div>
      <main class="broadcast-main"><aside class="timing-tower"><div class="timing-title"><b>POS</b><span id="live-lap-label">TEMPO</span></div><div id="timing-list"></div></aside>
      <section class="track-stage"><div class="track-heading"><div><span class="live-pill">● LIVE</span><h1>${sessionName()}</h1></div><div class="speed-bank">${[1,2,3,4,8].map(x=>`<button data-live="speed" data-value="${x}" class="${sim.speed===x?"is-active":""}">${x}×</button>`).join("")}<button data-live="pause">${sim.running?"PAUSAR":"INICIAR"}</button></div></div>
        <div class="track-map"><svg viewBox="0 0 1000 520" role="img" aria-label="Traçado de ${circuit.name}"><defs><filter id="track-glow"><feGaussianBlur stdDeviation="7" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path class="track-shadow" d="${circuit.trackPath}"/><path id="live-track-line" class="track-line" d="${circuit.trackPath}"/><g id="car-layer">${sim.drivers.map((d,i)=>`<g class="map-car ${d.controlled?"is-player":""}" data-car="${d.id}"><circle r="${d.controlled?11:7}" fill="${d.team.color}"/><text x="0" y="3">${i+1}</text></g>`).join("")}</g></svg><div class="race-control"><b>DIREÇÃO DE PROVA</b><span id="race-message">${sim.events[0]}</span></div></div>
        <div id="session-summary" class="session-summary" hidden></div>
      </section><aside class="pit-wall"><div class="pit-tabs"><button class="is-active">PIT WALL</button><button>TELEMETRIA</button></div><div id="driver-selector" class="driver-selector">${career.team.drivers.map(d=>`<button data-live="select-driver" data-id="${d.id}" class="${sim.selectedId===d.id?"is-active":""}"><img src="assets/official/driver-${d.name.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-")}.webp" alt="${d.name}"><span>${d.name.split(" ").pop()}</span></button>`).join("")}</div><div id="telemetry-panel"></div></aside></main>
      <footer class="broadcast-footer"><span id="phase-progress">${sessionName()}</span><div class="footer-track"><i id="phase-bar"></i></div><span>${circuit.laps} VOLTAS · ${circuit.country.toUpperCase()}</span></footer>
    </div>`;
    path=root.querySelector("#live-track-line");pathLength=path?.getTotalLength()||1;
    root.onclick=handleClick; root.oninput=handleInput;
    paint(true);
  }

  function telemetryHtml(){
    const d=selected(), setup=career.technical.setup;
    if(sim.phase==="practice")return `<section class="driver-live"><h2>${NATIONALITY[d.name]||"🏁"} ${d.name}</h2><p>${d.team.name} · ${d.active?"NA PISTA":"NOS BOXES"}</p><div class="telemetry-grid"><div><b id="tel-speed">${Math.round(d.speed)}</b><span>KM/H</span></div><div><b id="tel-tyre">${Math.round(d.tyre)}%</b><span>PNEUS</span></div><div><b id="tel-temp">${Math.round(d.engineTemp)}°</b><span>MOTOR</span></div><div><b id="tel-energy">${Math.round(d.energy)}%</b><span>ENERGIA</span></div></div><button class="pit-primary" data-live="toggle-track">${d.active?"RECOLHER AOS BOXES":"ENVIAR PARA A PISTA"}</button><h3>ACERTO EM TEMPO REAL</h3>${[["frontWing","ASA DIANTEIRA"],["rearWing","ASA TRASEIRA"],["suspension","SUSPENSÃO"],["brakeBalance","BALANÇO DE FREIO"]].map(([k,l])=>`<label class="live-range"><span>${l}<b>${setup[k]}</b></span><input data-setup="${k}" type="range" min="0" max="100" value="${setup[k]}"></label>`).join("")}</section>`;
    if(sim.phase==="qualifying")return `<section class="driver-live"><h2>${NATIONALITY[d.name]||"🏁"} ${d.name}</h2><p>${d.eliminated?"ELIMINADO":d.active?"VOLTA RÁPIDA":"NOS BOXES"}</p><div class="telemetry-grid"><div><b id="tel-speed">${Math.round(d.speed)}</b><span>KM/H</span></div><div><b id="tel-tyre">${Math.round(d.tyre)}%</b><span>PNEUS</span></div><div><b>${d.best?lapTime(d.best):"—"}</b><span>MELHOR</span></div><div><b>${d.position}</b><span>POSIÇÃO</span></div></div><button class="pit-primary" data-live="toggle-track" ${d.eliminated?"disabled":""}>${d.active?"ABORTAR VOLTA":"ENVIAR PARA VOLTA RÁPIDA"}</button><p class="strategy-note">Q1 elimina 6 pilotos, Q2 elimina mais 6 e Q3 define as dez primeiras posições.</p></section>`;
    if(sim.phase==="race")return `<section class="driver-live"><h2>${NATIONALITY[d.name]||"🏁"} ${d.name}</h2><p>P${d.position} · VOLTA ${Math.min(circuit.laps,Math.floor(d.progress)+1)}/${circuit.laps}</p><div class="telemetry-grid"><div><b id="tel-speed">${Math.round(d.speed)}</b><span>KM/H</span></div><div><b id="tel-tyre">${Math.round(d.tyre)}%</b><span>${d.compound}</span></div><div><b id="tel-temp">${Math.round(d.engineTemp)}°</b><span>MOTOR</span></div><div><b id="tel-energy">${Math.round(d.energy)}%</b><span>ENERGIA</span></div></div><label class="control-label">RITMO<select data-strategy="paceMode"><option value="conserve" ${d.paceMode==="conserve"?"selected":""}>Poupar</option><option value="normal" ${d.paceMode==="normal"?"selected":""}>Normal</option><option value="attack" ${d.paceMode==="attack"?"selected":""}>Atacar</option></select></label><label class="control-label">MOTOR<select data-strategy="engineMode"><option value="conserve" ${d.engineMode==="conserve"?"selected":""}>Conservar</option><option value="standard" ${d.engineMode==="standard"?"selected":""}>Padrão</option><option value="push" ${d.engineMode==="push"?"selected":""}>Potência máxima</option></select></label><label class="control-label">PRÓXIMO PNEU<select data-strategy="targetCompound"><option>MACIO</option><option selected>MÉDIO</option><option>DURO</option><option>INTERMEDIÁRIO</option></select></label><label class="control-label">JANELA DE PIT<input data-strategy="pitLap" type="number" min="2" max="${circuit.laps-1}" value="${d.pitLap}"></label><button class="pit-primary pit-stop" data-live="pit" ${d.inPit?"disabled":""}>${d.inPit?"PIT STOP EM ANDAMENTO":"CHAMAR PARA O BOX"}</button><p class="strategy-note">Atacar melhora o ritmo, mas aumenta desgaste e temperatura. Poupar recupera energia e protege o carro.</p></section>`;
    return `<section class="driver-live"><h2>Fim de semana concluído</h2><p>Resultado e troféu foram gravados no save.</p></section>`;
  }

  function paint(force=false){
    const now=performance.now();if(!force&&now-sim.lastPaint<110)return;sim.lastPaint=now;
    const sorted=order();sorted.forEach((d,i)=>d.position=i+1);
    const list=root.querySelector("#timing-list");if(list)list.innerHTML=sorted.map((d,i)=>`<button class="timing-row ${d.controlled?"is-player":""} ${d.eliminated?"is-out":""}" data-live="select-driver" data-id="${d.id}"><b>${i+1}</b><i style="--team:${d.team.color}"></i><span>${NATIONALITY[d.name]||""} ${d.name.split(" ").pop().slice(0,10)}</span><small>${sim.phase==="race"?`${Math.min(circuit.laps,Math.floor(d.progress)+1)}/${circuit.laps}`:d.best?lapTime(d.best):"NO TIME"}</small></button>`).join("");
    const lapLabel=root.querySelector("#live-lap-label");if(lapLabel)lapLabel.textContent=sim.phase==="race"?`VOLTA ${Math.min(circuit.laps,Math.floor(sorted[0]?.progress||0)+1)}/${circuit.laps}`:"TEMPO";
    const clock=root.querySelector("#live-clock");if(clock)clock.textContent=fmtTime(sim.duration-sim.elapsed);
    const bar=root.querySelector("#phase-bar");if(bar)bar.style.width=`${clamp(sim.elapsed/sim.duration*100)}%`;
    const panel=root.querySelector("#telemetry-panel");if(panel&&force)panel.innerHTML=telemetryHtml();else if(panel){const d=selected();const s=panel.querySelector("#tel-speed"),t=panel.querySelector("#tel-tyre"),m=panel.querySelector("#tel-temp"),e=panel.querySelector("#tel-energy");if(s)s.textContent=Math.round(d.speed);if(t)t.textContent=`${Math.round(d.tyre)}%`;if(m)m.textContent=`${Math.round(d.engineTemp)}°`;if(e)e.textContent=`${Math.round(d.energy)}%`;}
    for(const d of sim.drivers){const car=root.querySelector(`[data-car="${d.id}"]`);if(!car||d.eliminated&&sim.phase==="qualifying"){if(car)car.style.opacity=".15";continue}const point=path?.getPointAtLength(((d.progress%1)+1)%1*pathLength);if(point)car.setAttribute("transform",`translate(${point.x} ${point.y})`);car.style.opacity=d.active||sim.phase==="race"?"1":".32";}
  }

  function practiceTick(dt){
    for(const d of sim.drivers){if(!d.controlled)d.active=rng(`${d.id}:${sim.practice}:${Math.floor(sim.elapsed/4)}`)>.24;if(!d.active)continue;const setup=career.technical.setup,fit=100-(Math.abs(setup.frontWing-(circuit.aero>78?72:circuit.power>82?38:54))*.3+Math.abs(setup.suspension-(circuit.tyre>75?62:48))*.2);const pace=(d.overall*.54+career.team.overall*.18+fit*.28)/100;d.progress+=dt*(.065+pace*.024);d.speed=190+pace*125+rng(`${d.id}:${Math.floor(sim.elapsed*4)}`)*25;d.tyre=clamp(d.tyre-dt*(.10+circuit.tyre/900));d.engineTemp=clamp(88+d.speed/18,80,125);d.energy=clamp(d.energy-dt*.11);if(Math.floor(d.progress)>d.laps){d.laps=Math.floor(d.progress);const time=104-pace*24+rng(`${d.id}:lap:${d.laps}`)*4;d.last=time;d.best=Math.min(d.best??999,time);}}
  }
  function qualifyingTick(dt){
    const contenders=sim.drivers.filter(d=>!d.eliminated).slice(0,activeCount());
    for(const d of contenders){if(!d.controlled)d.active=rng(`${d.id}:${sim.segment}:${Math.floor(sim.elapsed/3)}`)>.15;if(!d.active)continue;const pace=(d.overall*.72+(d.teamId===career.team.id?.replace("team-2026-","")?career.team.overall:72)*.28)/100;d.progress+=dt*(.078+pace*.024);d.speed=215+pace*120;d.tyre=clamp(d.tyre-dt*.28);if(Math.floor(d.progress)>d.laps){d.laps=Math.floor(d.progress);const time=101-pace*22+rng(`${d.id}:${sim.segment}:${d.laps}`)*3.8;d.best=Math.min(d.best??999,time);}}
  }
  function raceTick(dt){
    const leader=order()[0];
    for(const d of sim.drivers){d.active=true;if(d.inPit){d.pitRemaining-=dt;d.speed=80;if(d.pitRemaining<=0){d.inPit=false;d.tyre=100;d.compound=d.targetCompound;sim.events.unshift(`${d.name} concluiu o pit stop e voltou à pista.`)}continue}const controlled=d.controlled,paceBoost=controlled?(d.paceMode==="attack"?.10:d.paceMode==="conserve"?-.055:0):rng(`${d.id}:mode:${Math.floor(sim.elapsed/9)}`)*.07;const engineBoost=controlled?(d.engineMode==="push"?.065:d.engineMode==="conserve"?-.035:0):.01;const tyreFactor=clamp(d.tyre/45,.45,1);const base=(d.overall/100)*.37+.63;const step=dt*(circuit.laps/sim.duration)*base*(1+paceBoost+engineBoost)*tyreFactor;d.progress+=step;d.speed=205+base*105+(paceBoost+engineBoost)*115;const wear=(.29+circuit.tyre/320)*(1+(paceBoost>0?.5:paceBoost<0?-.28:0));d.tyre=clamp(d.tyre-dt*wear);d.engineTemp=clamp(d.engineTemp+dt*((engineBoost>.03?2.2:-.65)+(d.engineTemp<99?.5:0)),82,132);d.energy=clamp(d.energy+dt*(d.paceMode==="conserve"?2:d.paceMode==="attack"?-2.4:.25));if(controlled&&Math.floor(d.progress)>=d.pitLap&&d.tyre<42&&!d.inPit)startPit(d);if(d.tyre<9)d.progress-=dt*.08;if(d.engineTemp>124)d.progress-=dt*.05;}
    if(leader&&leader.progress>=circuit.laps)finishRace();
    const mark=Math.floor(sim.elapsed/11);if(mark>0&&mark>sim.lastEvent){sim.lastEvent=mark;const messages=["Bandeira amarela no setor 2. Sem ultrapassagens.","Pista liberada. Bandeira verde.","DRS habilitado pela direção de prova.","Nuvens se aproximam, chance de chuva aumentando.","Detritos recolhidos; ritmo normal."];sim.events.unshift(messages[(mark-1)%messages.length]);const msg=root.querySelector("#race-message");if(msg)msg.textContent=sim.events[0];}
  }

  function tick(now){const raw=Math.min(.08,(now-sim.lastFrame)/1000);sim.lastFrame=now;if(sim.running&&!sim.finished){const dt=raw*sim.speed;sim.elapsed+=dt;if(sim.phase==="practice")practiceTick(dt);if(sim.phase==="qualifying")qualifyingTick(dt);if(sim.phase==="race")raceTick(dt);if(sim.elapsed>=sim.duration&&!sim.finished)finishSession();paint()}raf=requestAnimationFrame(tick)}

  function finishSession(){sim.running=false;sim.finished=true;sim.elapsed=sim.duration;if(sim.phase==="practice")finishPractice();else if(sim.phase==="qualifying")finishQualifying();else if(sim.phase==="race")finishRace();}
  function finishPractice(){const sorted=order();career.technical.weekend.practiceRuns.push({session:`TL${sim.practice}`,pace:Math.round(100-(sorted[0]?.best||80)),setup:Math.round(Object.values(career.technical.setup).reduce((a,b)=>a+b,0)/4),tyreWear:Math.round(100-(selected()?.tyre||100))});career.technical.weekend.telemetry={pace:Math.round(100-(selected()?.best||80)),setup:Math.round(Object.values(career.technical.setup).reduce((a,b)=>a+b,0)/4),tyreWear:Math.round(100-(selected()?.tyre||100)),confidence:68+sim.practice*8};showSummary(`TL${sim.practice} CONCLUÍDO`,sorted.slice(0,5),sim.practice<3?`AVANÇAR PARA TL${sim.practice+1}`:"AVANÇAR PARA CLASSIFICAÇÃO");persist(`TL${sim.practice} concluído em ${circuit.name}.`)}
  function finishQualifying(){const sorted=order().filter(d=>!d.eliminated);if(sim.segment==="Q1"){const out=sorted.slice(16);out.forEach(d=>d.eliminated=true);sim.q1Out=out;showSummary("Q1 CONCLUÍDO",sorted.slice(0,16),"AVANÇAR PARA Q2");}else if(sim.segment==="Q2"){const out=sorted.slice(10);out.forEach(d=>d.eliminated=true);sim.q2Out=out;showSummary("Q2 CONCLUÍDO",sorted.slice(0,10),"AVANÇAR PARA Q3");}else{const top=sorted.slice(0,10),grid=[...top,...sim.q2Out,...sim.q1Out];grid.forEach((d,i)=>d.position=i+1);sim.grid=grid;career.technical.weekend.qualifying=grid.map(d=>({driverId:d.id,name:d.name,teamId:d.teamId,position:d.position,bestLap:d.best}));career.technical.weekend.phase="grid-set";showSummary("GRID DE LARGADA DEFINIDO",grid.slice(0,10),"INICIAR CORRIDA");persist(`Grid completo definido para ${circuit.name}.`);}}
  function showSummary(title,drivers,button){const box=root.querySelector("#session-summary");if(!box)return;box.hidden=false;box.innerHTML=`<div class="summary-card"><p class="eyebrow">RESULTADO OFICIAL</p><h2>${title}</h2><div class="summary-results">${drivers.slice(0,10).map((d,i)=>`<span><b>P${i+1}</b><i style="--team:${d.team.color}"></i>${NATIONALITY[d.name]||""} ${d.name}<small>${d.best?lapTime(d.best):"—"}</small></span>`).join("")}</div><button class="pit-primary" data-live="next-session">${button}</button></div>`;}
  function resetDrivers(keepGrid=false){for(const [i,d] of sim.drivers.entries()){d.active=false;d.best=null;d.last=null;d.tyre=100;d.energy=100;d.engineTemp=92;d.speed=0;d.laps=0;d.inPit=false;if(!keepGrid)d.progress=(22-i)*.002;}}
  function nextSession(){const box=root.querySelector("#session-summary");if(box)box.hidden=true;sim.finished=false;sim.elapsed=0;sim.running=false;if(sim.phase==="practice"&&sim.practice<3){sim.practice++;sim.segment=`TL${sim.practice}`;sim.duration=18;resetDrivers();}else if(sim.phase==="practice"){sim.phase="qualifying";sim.segment="Q1";sim.duration=18;resetDrivers();}else if(sim.phase==="qualifying"&&sim.segment==="Q1"){sim.segment="Q2";sim.duration=15;resetDrivers(true);}else if(sim.phase==="qualifying"&&sim.segment==="Q2"){sim.segment="Q3";sim.duration=12;resetDrivers(true);}else if(sim.phase==="qualifying"){startRace();return}render();}
  function startRace(){sim.phase="race";sim.segment="RACE";sim.duration=55;sim.elapsed=0;sim.finished=false;sim.running=false;sim.raceStarted=true;const grid=sim.grid||order();sim.drivers=grid.map((d,i)=>({...d,eliminated:false,active:true,progress:(grid.length-i)*.003,position:i+1,best:null,last:null,tyre:100,compound:i<10?"MACIO":"MÉDIO",engineTemp:91,energy:100,pitLap:Math.max(5,Math.round(circuit.laps*(i%2?.48:.39))),inPit:false}));sim.events.unshift("Formação concluída. Aguardando as cinco luzes.");render();}
  function startPit(d){d.inPit=true;d.pitRemaining=2.6+(rng(`${d.id}:pit:${Math.floor(d.progress)}`)*.9);d.progress=Math.max(0,d.progress-.36);sim.events.unshift(`${d.name} entra nos boxes para pneus ${d.targetCompound.toLowerCase()}.`);}
  function finishRace(){if(sim.finished&&sim.phase==="podium")return;sim.running=false;sim.finished=true;const result=order();result.forEach((d,i)=>d.position=i+1);career.technical.weekend.raceResult=result.map((d,i)=>({driverId:d.id,name:d.name,teamId:d.teamId,position:i+1,points:POINTS[i]||0,compound:d.compound,tyre:Math.round(d.tyre)}));career.technical.weekend.phase="completed";career.trophies||=[];career.trophies.unshift({id:`trophy-${circuit.id}-${Date.now()}`,round:career.technical.weekend.round+1,circuitId:circuit.id,grandPrix:circuit.grandPrix,country:circuit.country,flag:circuit.flag,winner:result[0].name,podium:result.slice(0,3).map(d=>({name:d.name,team:d.team.name,flag:NATIONALITY[d.name]||"🏁"}))});career.history.push({week:career.week,type:"race",text:`${result[0].name} venceu ${circuit.grandPrix}; ${career.team.name}: ${result.filter(d=>d.controlled).map(d=>`${d.name} P${d.position}`).join(" e ")}.`});persist(`Corrida concluída: ${result[0].name} venceu.`);sim.phase="podium";renderPodium(result);}
  function renderPodium(result){cancelAnimationFrame(raf);root.innerHTML=`<section class="podium-screen"><div class="confetti-layer"></div><button class="broadcast-exit" data-live="exit">SAIR E SALVAR</button><p class="eyebrow">${circuit.flag} ${circuit.grandPrix.toUpperCase()}</p><h1>PÓDIO</h1><div class="podium-stage"><article class="podium-place second"><span>🥈</span><img src="assets/official/driver-${slug(result[1].name)}.webp" alt="${result[1].name}"><h2>${NATIONALITY[result[1].name]} ${result[1].name}</h2><b>${result[1].team.name}</b><i>2</i></article><article class="podium-place first"><span>🏆</span><img src="assets/official/driver-${slug(result[0].name)}.webp" alt="${result[0].name}"><h2>${NATIONALITY[result[0].name]} ${result[0].name}</h2><b>${result[0].team.name}</b><i>1</i></article><article class="podium-place third"><span>🥉</span><img src="assets/official/driver-${slug(result[2].name)}.webp" alt="${result[2].name}"><h2>${NATIONALITY[result[2].name]} ${result[2].name}</h2><b>${result[2].team.name}</b><i>3</i></article></div><div class="podium-actions"><button class="pit-primary" data-live="exit">VOLTAR AO PADDOCK</button></div></section>`;root.onclick=handleClick;}
  function slug(v){return v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-")}
  function persist(message){career.updatedAt=new Date().toISOString();callbacks.onSave?.(clone(career),message)}
  function exitLive(){cancelAnimationFrame(raf);persist("Fim de semana salvo.");root.hidden=true;root.innerHTML="";callbacks.onExit?.(clone(career));}
  function handleInput(e){const d=selected();if(e.target.dataset.setup){career.technical.setup[e.target.dataset.setup]=Number(e.target.value);e.target.previousElementSibling.querySelector("b").textContent=e.target.value;persist("Acerto atualizado durante a sessão.")}if(e.target.dataset.strategy){d[e.target.dataset.strategy]=e.target.type==="number"?Number(e.target.value):e.target.value;}}
  function handleClick(e){const b=e.target.closest("[data-live]");if(!b)return;const action=b.dataset.live;if(action==="exit")exitLive();if(action==="speed"){sim.speed=Number(b.dataset.value);root.querySelectorAll('[data-live="speed"]').forEach(x=>x.classList.toggle("is-active",x===b));}if(action==="pause"){sim.running=!sim.running;b.textContent=sim.running?"PAUSAR":"CONTINUAR";}if(action==="select-driver"){sim.selectedId=b.dataset.id;root.querySelectorAll('[data-live="select-driver"]').forEach(x=>x.classList.toggle("is-active",x.dataset.id===sim.selectedId));const p=root.querySelector("#telemetry-panel");if(p)p.innerHTML=telemetryHtml();}if(action==="toggle-track"){const d=selected();d.active=!d.active;b.textContent=d.active?"RECOLHER AOS BOXES":"ENVIAR PARA A PISTA";}if(action==="next-session")nextSession();if(action==="pit")startPit(selected());}
  render();raf=requestAnimationFrame(tick);
  return {destroy(){cancelAnimationFrame(raf);root.hidden=true;root.innerHTML=""}};
}
