import { CIRCUITS_2026, DRIVERS_2026 } from "./data/game-data.mjs";
import { recordRaceResult, recordSprintResult } from "./engine.mjs";

const TEAM = {
  mercedes:{name:"Mercedes",short:"MER",color:"#00d2be"}, ferrari:{name:"Ferrari",short:"FER",color:"#e8002d"}, mclaren:{name:"McLaren",short:"MCL",color:"#ff8700"},
  "red-bull":{name:"Red Bull",short:"RBR",color:"#3671c6"}, "racing-bulls":{name:"Racing Bulls",short:"RB",color:"#6692ff"}, alpine:{name:"Alpine",short:"ALP",color:"#2293d1"},
  haas:{name:"Haas",short:"HAS",color:"#b6babd"}, audi:{name:"Audi",short:"AUD",color:"#f50537"}, williams:{name:"Williams",short:"WIL",color:"#64c4ff"},
  "aston-martin":{name:"Aston Martin",short:"AMR",color:"#006f62"}, cadillac:{name:"Cadillac",short:"CAD",color:"#c9a66b"},
};
const NATIONALITY = {"Kimi Antonelli":"it","George Russell":"gb","Lewis Hamilton":"gb","Charles Leclerc":"mc","Lando Norris":"gb","Oscar Piastri":"au","Max Verstappen":"nl","Isack Hadjar":"fr","Liam Lawson":"nz","Arvid Lindblad":"gb","Pierre Gasly":"fr","Franco Colapinto":"ar","Oliver Bearman":"gb","Esteban Ocon":"fr","Gabriel Bortoleto":"br","Nico Hülkenberg":"de","Carlos Sainz":"es","Alexander Albon":"th","Fernando Alonso":"es","Lance Stroll":"ca","Valtteri Bottas":"fi","Sergio Pérez":"mx"};
const COUNTRY_LABEL={it:"ITA",gb:"GBR",mc:"MON",au:"AUS",nl:"NED",fr:"FRA",nz:"NZL",ar:"ARG",br:"BRA",de:"GER",es:"ESP",th:"THA",ca:"CAN",fi:"FIN",mx:"MEX"};
const SPEED_FACTOR={1:1,2:1.25,3:1.8,4:3.33,8:20};
const PIT_BASE={mercedes:2.35,ferrari:2.45,mclaren:2.32,"red-bull":2.28,"racing-bulls":2.65,alpine:2.75,haas:2.85,audi:2.70,williams:2.65,"aston-martin":2.72,cadillac:2.95};
const COMPOUNDS={MACIO:{wear:1.28,dry:1.025,wet:.62,temp:98},MÉDIO:{wear:1,dry:1,wet:.64,temp:94},DURO:{wear:.76,dry:.982,wet:.66,temp:90},INTERMEDIÁRIO:{wear:1.05,dry:.82,wet:1.02,temp:82},CHUVA:{wear:.86,dry:.68,wet:1.06,temp:72}};
const CONTROL={GREEN:{icon:"🟢",label:"PISTA LIVRE"},YELLOW:{icon:"🟡",label:"BANDEIRA AMARELA"},VSC:{icon:"VSC",label:"VIRTUAL SAFETY CAR"},SC:{icon:"SC",label:"SAFETY CAR"},RED:{icon:"🔴",label:"BANDEIRA VERMELHA"},BLACK_WHITE:{icon:"◩",label:"PRETA E BRANCA"},CHEQUERED:{icon:"🏁",label:"BANDEIRA QUADRICULADA"}};
const fmtTime=s=>{const n=Math.max(0,Math.ceil(s)),m=Math.floor(n/60),x=n%60;return `${String(m).padStart(2,"0")}:${String(x).padStart(2,"0")}`};
const clone=value=>JSON.parse(JSON.stringify(value));
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const rng=(seed)=>{let h=2166136261;for(const c of String(seed))h=Math.imul(h^c.charCodeAt(0),16777619);h+=0x6D2B79F5;h=Math.imul(h^(h>>>15),h|1);h^=h+Math.imul(h^(h>>>7),h|61);return((h^(h>>>14))>>>0)/4294967296};
const lapTime=n=>{const sec=Math.max(58,n);return `${Math.floor(sec/60)}:${(sec%60).toFixed(3).padStart(6,"0")}`};
const slug=v=>v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-");
const flagHtml=name=>{const code=NATIONALITY[name]||"";return code?`<span class="driver-flag"><img src="https://flagcdn.com/24x18/${code}.png" alt="${COUNTRY_LABEL[code]}" loading="eager"><em>${COUNTRY_LABEL[code]}</em></span>`:`<span class="driver-flag"><em>FIA</em></span>`};

export const simulationSpeedMultiplier=value=>SPEED_FACTOR[value]||1;
export function rankRaceDrivers(drivers,lapSeconds){return drivers.slice().sort((a,b)=>Number(a.retired)-Number(b.retired)||(b.progress-(b.penalty||0)/lapSeconds)-(a.progress-(a.penalty||0)/lapSeconds))}
export function calculatePitTiming({pitLoss,teamId,crew=72,seed="pit"}){const service=clamp((PIT_BASE[teamId]||2.8)+(72-crew)*.012+(rng(seed)-.5)*.45,1.95,4.8),entry=pitLoss*.44,exit=pitLoss-entry;return{entry,service,exit,total:entry+service+exit}}

function driverGrid(career,circuit){
  return DRIVERS_2026.filter(d=>d.seasonStatus==="active").map((d,index)=>({
    ...d,team:TEAM[d.teamId],controlled:career.team.drivers.some(x=>x.id===d.id),position:index+1,progress:Math.max(0,(22-index)*.002),best:null,last:null,
    tyre:100,tyreTemp:88,compound:index%3===0?"MÉDIO":"MACIO",startCompound:index%3===0?"MÉDIO":"MACIO",usedCompounds:[],engine:92,engineTemp:92,energy:100,ers:100,fuel:100,damage:0,trackWarnings:0,penalty:0,status:"RUNNING",retired:false,drs:false,speed:0,laps:0,inPit:false,pitRemaining:0,pitStops:0,plannedStops:circuit.tyre>80?2:1,pitHistory:[],pit:null,pitCooldown:0,lastPitLap:-20,totalPitTime:0,lastPitService:null,active:false,
    paceMode:"normal",engineMode:"standard",ersMode:"balanced",targetCompound:index%3===0?"DURO":"MÉDIO",pitLap:Math.max(8,Math.round(circuit.laps*.42)+(index%5)),eliminated:false,score:0,
  }));
}

export function mountLiveWeekend(root,careerState,callbacks={}){
  let career=clone(careerState);
  const circuit=career.technical.weekend.circuit||CIRCUITS_2026[0];
  const qa=new URLSearchParams(location.search).has("qa"),durationFor=phase=>qa?180:phase==="Q1"?1080:phase==="Q2"?900:phase==="Q3"?720:720;
  const rainEvent=rng(`${career.saveId}:${circuit.id}:weather`)>0.64;
  const sim={phase:"practice",segment:"TL1",practice:1,elapsed:0,duration:durationFor("TL1"),speed:1,running:false,finished:false,drivers:driverGrid(career,circuit),selectedId:career.team.drivers[0]?.id,grid:null,sprintGrid:null,events:["Direção de prova: pista liberada."],radio:[{sender:"Lara",text:"Pista aberta. Confirme o programa dos dois carros.",priority:"normal"}],lastFrame:performance.now(),lastPaint:0,q1Out:[],q2Out:[],raceStarted:false,eventIndex:0,nextEventAt:240,raceControl:"GREEN",neutralRemaining:0,stats:{safetyCars:0,virtualSafetyCars:0,redFlags:0,retirements:0,penalties:0},weather:{condition:"SECO",air:24+Math.round(rng(circuit.id)*8),track:31+Math.round(rng(`${circuit.id}:track`)*12),rain:0,wet:0,forecast:rainEvent?"CHUVA PREVISTA":"ESTÁVEL"}};
  let raf=0,path=null,pathLength=1;

  const selected=()=>sim.drivers.find(d=>d.id===sim.selectedId)||sim.drivers[0];
  const isRaceSession=()=>sim.phase==="race"||sim.phase==="sprint";
  const isQualifyingSession=()=>sim.phase==="qualifying"||sim.phase==="sprint-qualifying";
  const sessionLaps=()=>sim.phase==="sprint"?Math.max(18,Math.round(circuit.laps*.34)):circuit.laps;
  const sessionName=()=>sim.phase==="practice"?`TREINO LIVRE ${sim.practice}`:sim.phase==="sprint-qualifying"?"CLASSIFICAÇÃO SPRINT":sim.phase==="sprint"?"SPRINT":sim.phase==="qualifying"?sim.segment:sim.phase==="race"?"CORRIDA":"PÓDIO";
  const sessionColor=()=>sim.phase==="race"?"#e8002d":sim.phase==="sprint"?"#ff5c00":isQualifyingSession()?"#b45cff":"#d9a632";
  const adjustedProgress=d=>d.progress-(d.penalty||0)/circuit.lapSeconds;
  const order=()=>isRaceSession()?rankRaceDrivers(sim.drivers,circuit.lapSeconds):sim.drivers.slice().sort((a,b)=>(a.best??999)-(b.best??999));
  const activeCount=()=>sim.segment==="Q2"?16:sim.segment==="Q3"?10:22;
  const leader=()=>order().find(d=>!d.retired);
  const gapText=(d,lead=leader())=>{if(d.retired)return "DNF";if(d===lead)return "LÍDER";const gap=Math.max(0,adjustedProgress(lead)-adjustedProgress(d));return gap>=1?`+${Math.floor(gap)} VOLTA${gap>=2?"S":""}`:`+${(gap*circuit.lapSeconds).toFixed(3)}`};
  const raceControlMeta=()=>CONTROL[sim.raceControl]||CONTROL.GREEN;

  function render(){
    const rc=raceControlMeta();root.hidden=false;
    root.innerHTML=`<div class="broadcast-shell" style="--session:${sessionColor()}">
      <header class="broadcast-header"><div class="broadcast-brand"><img src="assets/media/capa-logo-horizontal.webp" alt="F1 Vale Gold Edition"><span>AO VIVO</span></div><div class="broadcast-event"><b>${circuit.flag} ${circuit.grandPrix} ${circuit.sprint?'<em class="sprint-badge">SPRINT</em>':""}</b><small>ETAPA ${circuit.round||CIRCUITS_2026.findIndex(c=>c.id===circuit.id)+1} · ${circuit.name}</small></div><div class="race-control-status" id="race-control-status" data-status="${sim.raceControl}"><strong>${rc.icon}</strong><span>${rc.label}</span></div><div class="broadcast-clock"><small>${sessionName()}</small><strong id="live-clock">${fmtTime(sim.duration)}</strong></div><button class="broadcast-exit" data-live="exit">SAIR E SALVAR</button></header>
      <div class="sponsor-ribbon"><img src="assets/official/sponsor-pirelli.webp" alt="Pirelli"><img src="assets/official/sponsor-dhl.webp" alt="DHL"><img src="assets/official/sponsor-aws.webp" alt="AWS"><img src="assets/official/sponsor-aramco.webp" alt="Aramco"><span>TRANSMISSÃO OFICIAL DA SUA EQUIPE</span></div>
      <main class="broadcast-main"><aside class="timing-tower"><div class="timing-title"><b>POS</b><span id="live-lap-label">TEMPO</span></div><div id="timing-list"></div></aside>
      <section class="track-stage"><div class="track-heading"><div><span class="live-pill">● LIVE</span><h1>${sessionName()}</h1><div class="weather-hud"><b id="weather-condition">${sim.weather.condition}</b><span id="weather-values">AR ${sim.weather.air}° · PISTA ${sim.weather.track}° · MOLHADA ${Math.round(sim.weather.wet)}%</span><small>${sim.weather.forecast}</small></div></div><div class="speed-bank">${[1,2,3,4,8].map(x=>`<button data-live="speed" data-value="${x}" class="${sim.speed===x?"is-active":""}">${x}×</button>`).join("")}<button data-live="pause">${sim.running?"PAUSAR":"INICIAR"}</button></div></div>
        <div class="track-map"><svg viewBox="0 0 1000 520" role="img" aria-label="Traçado de ${circuit.name}"><defs><filter id="track-glow"><feGaussianBlur stdDeviation="7" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path class="track-shadow" d="${circuit.trackPath}"/><path id="live-track-line" class="track-line" d="${circuit.trackPath}"/><g id="car-layer">${sim.drivers.map((d,i)=>`<g class="map-car ${d.controlled?"is-player":""}" data-car="${d.id}"><circle r="${d.controlled?11:7}" fill="${d.team.color}"/><text x="0" y="3">${i+1}</text></g>`).join("")}</g></svg><div class="race-control"><div class="race-control-flag" id="race-flag-icon" data-status="${sim.raceControl}">${rc.icon}</div><div><b id="race-flag-label">${rc.label}</b><span id="race-message">${sim.events[0]}</span></div></div></div>
        <div id="session-summary" class="session-summary" hidden></div>
      </section><aside class="pit-wall"><div class="pit-tabs"><button class="is-active">PIT WALL</button><button>TELEMETRIA</button></div><div id="driver-selector" class="driver-selector">${career.team.drivers.map(d=>`<button data-live="select-driver" data-id="${d.id}" class="${sim.selectedId===d.id?"is-active":""}"><img src="assets/official/driver-${slug(d.name)}.webp" alt="${d.name}"><span>${flagHtml(d.name)} ${d.name.split(" ").pop()}</span></button>`).join("")}</div><div id="telemetry-panel"></div></aside></main>
      <footer class="broadcast-footer"><span id="phase-progress">${sessionName()}</span><div class="footer-track"><i id="phase-bar"></i></div><span>${sessionLaps()} VOLTAS · ${circuit.country.toUpperCase()}</span></footer>
    </div>`;
    path=root.querySelector("#live-track-line");pathLength=path?.getTotalLength()||1;root.onclick=handleClick;root.oninput=handleInput;paint(true);
  }

  function pitDetail(d){if(!d.inPit||!d.pit)return d.pitHistory.length?`Último pit: serviço ${d.pitHistory.at(-1).service.toFixed(2)}s · total ${d.pitHistory.at(-1).total.toFixed(2)}s`:"Nenhuma parada realizada";const p=d.pit,stage=p.elapsed<p.entry?"ENTRADA":p.elapsed<p.entry+p.service?"SERVIÇO":"SAÍDA";return `${stage} · ${Math.max(0,d.pitRemaining).toFixed(1)}s restantes · total previsto ${p.total.toFixed(2)}s`}
  function telemetryHtml(){
    const d=selected(),setup=career.technical.setup;
    if(sim.phase==="practice")return `<section class="driver-live"><h2>${flagHtml(d.name)} ${d.name}</h2><p>${d.team.name} · ${d.active?"NA PISTA":"NOS BOXES"}</p><div class="telemetry-grid"><div><b id="tel-speed">${Math.round(d.speed)}</b><span>KM/H</span></div><div><b id="tel-tyre">${Math.round(d.tyre)}%</b><span>PNEUS</span></div><div><b id="tel-temp">${Math.round(d.engineTemp)}°</b><span>MOTOR</span></div><div><b id="tel-energy">${Math.round(d.energy)}%</b><span>ENERGIA</span></div></div><button class="pit-primary" data-live="toggle-track">${d.active?"RECOLHER AOS BOXES":"ENVIAR PARA A PISTA"}</button><h3>ACERTO EM TEMPO REAL</h3>${[["frontWing","ASA DIANTEIRA"],["rearWing","ASA TRASEIRA"],["suspension","SUSPENSÃO"],["brakeBalance","BALANÇO DE FREIO"]].map(([k,l])=>`<label class="live-range"><span>${l}<b>${setup[k]}</b></span><input data-setup="${k}" type="range" min="0" max="100" value="${setup[k]}"></label>`).join("")}</section>`;
    if(isQualifyingSession())return `<section class="driver-live"><h2>${flagHtml(d.name)} ${d.name}</h2><p>${d.eliminated?"ELIMINADO":d.active?"VOLTA RÁPIDA":"NOS BOXES"}</p><div class="telemetry-grid"><div><b id="tel-speed">${Math.round(d.speed)}</b><span>KM/H</span></div><div><b id="tel-tyre">${Math.round(d.tyre)}%</b><span>PNEUS</span></div><div><b>${d.best?lapTime(d.best):"—"}</b><span>MELHOR</span></div><div><b>${d.position}</b><span>POSIÇÃO</span></div></div><button class="pit-primary" data-live="toggle-track" ${d.eliminated?"disabled":""}>${d.active?"ABORTAR VOLTA":"ENVIAR PARA VOLTA RÁPIDA"}</button><p class="strategy-note">${sim.phase==="sprint-qualifying"?"Sessão curta que define o grid da Sprint.":"Q1 elimina 6 pilotos, Q2 elimina mais 6 e Q3 define as dez primeiras posições."}</p></section>`;
    if(isRaceSession())return `<section class="driver-live"><h2>${flagHtml(d.name)} ${d.name}</h2><p>P${d.position} · ${d.retired?d.status:`VOLTA ${Math.min(sessionLaps(),Math.floor(d.progress)+1)}/${sessionLaps()} · ${gapText(d)}`}</p><div class="telemetry-grid telemetry-grid--dense"><div><b id="tel-speed">${Math.round(d.speed)}</b><span>KM/H ${d.drs?"· DRS":""}</span></div><div><b id="tel-tyre">${Math.round(d.tyre)}%</b><span>${d.compound}</span></div><div><b id="tel-fuel">${Math.round(d.fuel)}%</b><span>COMBUSTÍVEL</span></div><div><b id="tel-ers">${Math.round(d.ers)}%</b><span>ERS</span></div><div><b id="tel-damage">${Math.round(d.damage)}%</b><span>DANOS</span></div><div><b id="tel-stops">${d.pitStops}/${d.plannedStops}</b><span>PARADAS</span></div></div><div class="pit-timing"><b>TEMPO DE BOX</b><span>${pitDetail(d)}</span><small>Perda-base desta pista: ${circuit.pitLoss}s + serviço</small></div><label class="control-label">RITMO<select data-strategy="paceMode"><option value="conserve" ${d.paceMode==="conserve"?"selected":""}>Poupar</option><option value="normal" ${d.paceMode==="normal"?"selected":""}>Normal</option><option value="attack" ${d.paceMode==="attack"?"selected":""}>Atacar</option></select></label><label class="control-label">MOTOR<select data-strategy="engineMode"><option value="conserve" ${d.engineMode==="conserve"?"selected":""}>Conservar</option><option value="standard" ${d.engineMode==="standard"?"selected":""}>Padrão</option><option value="push" ${d.engineMode==="push"?"selected":""}>Potência máxima</option></select></label><label class="control-label">ERS<select data-strategy="ersMode"><option value="harvest" ${d.ersMode==="harvest"?"selected":""}>Recarregar</option><option value="balanced" ${d.ersMode==="balanced"?"selected":""}>Equilibrado</option><option value="deploy" ${d.ersMode==="deploy"?"selected":""}>Atacar</option></select></label><label class="control-label">PLANO<select data-strategy="plannedStops">${[1,2,3].map(n=>`<option value="${n}" ${d.plannedStops===n?"selected":""}>${n} parada${n>1?"s":""}</option>`).join("")}</select></label><label class="control-label">PRÓXIMO PNEU<select data-strategy="targetCompound">${["MACIO","MÉDIO","DURO","INTERMEDIÁRIO","CHUVA"].map(c=>`<option ${d.targetCompound===c?"selected":""}>${c}</option>`).join("")}</select></label><label class="control-label">PRÓXIMO PIT<input data-strategy="pitLap" type="number" min="2" max="${sessionLaps()-1}" value="${d.pitLap}"></label><button class="pit-primary pit-stop" data-live="pit" ${d.inPit||d.retired||d.pitCooldown>0?"disabled":""}>${d.inPit?pitDetail(d):d.retired?"CARRO FORA":d.pitCooldown>0?"AGUARDE UMA VOLTA":"CHAMAR PARA O BOX"}</button><div class="team-radio"><b>RÁDIO DA EQUIPE</b>${sim.radio.slice(0,3).map(r=>`<p class="${r.priority}"><strong>${r.sender}</strong> ${r.text}</p>`).join("")}</div></section>`;
    return `<section class="driver-live"><h2>Fim de semana concluído</h2><p>Resultado e troféu foram gravados no save.</p></section>`;
  }

  function paint(force=false){
    const now=performance.now();if(!force&&now-sim.lastPaint<110)return;sim.lastPaint=now;const sorted=order(),lead=sorted.find(d=>!d.retired);sorted.forEach((d,i)=>d.position=i+1);
    const list=root.querySelector("#timing-list");if(list)list.innerHTML=sorted.map((d,i)=>`<button class="timing-row ${d.controlled?"is-player":""} ${d.eliminated||d.retired?"is-out":""} ${d.inPit?"is-pit":""}" data-live="select-driver" data-id="${d.id}"><b>${i+1}</b><i style="--team:${d.team.color}"></i><span>${flagHtml(d.name)} <strong>${d.name.split(" ").pop().slice(0,10)}</strong></span><small>${isRaceSession()?(d.inPit?`PIT ${d.pitRemaining.toFixed(1)}s`:gapText(d,lead)):d.best?lapTime(d.best):"NO TIME"}</small></button>`).join("");
    const lapLabel=root.querySelector("#live-lap-label");if(lapLabel)lapLabel.textContent=isRaceSession()?`VOLTA ${Math.min(sessionLaps(),Math.floor(lead?.progress||0)+1)}/${sessionLaps()}`:"TEMPO";
    const clock=root.querySelector("#live-clock");if(clock)clock.textContent=fmtTime(isRaceSession()?sim.elapsed:sim.duration-sim.elapsed);
    const bar=root.querySelector("#phase-bar");if(bar)bar.style.width=`${clamp((isRaceSession()?(lead?.progress||0)/sessionLaps():sim.elapsed/sim.duration)*100)}%`;
    const meta=raceControlMeta(),rc=root.querySelector("#race-control-status"),ri=root.querySelector("#race-flag-icon"),rl=root.querySelector("#race-flag-label");if(rc){rc.dataset.status=sim.raceControl;rc.querySelector("strong").textContent=meta.icon;rc.querySelector("span").textContent=meta.label}if(ri){ri.dataset.status=sim.raceControl;ri.textContent=meta.icon}if(rl)rl.textContent=meta.label;
    const wc=root.querySelector("#weather-condition"),wv=root.querySelector("#weather-values");if(wc)wc.textContent=sim.weather.condition;if(wv)wv.textContent=`AR ${sim.weather.air}° · PISTA ${Math.round(sim.weather.track)}° · MOLHADA ${Math.round(sim.weather.wet)}%`;
    const panel=root.querySelector("#telemetry-panel");if(panel&&(force||isRaceSession()))panel.innerHTML=telemetryHtml();else if(panel){const d=selected(),s=panel.querySelector("#tel-speed"),t=panel.querySelector("#tel-tyre"),m=panel.querySelector("#tel-temp"),e=panel.querySelector("#tel-energy");if(s)s.textContent=Math.round(d.speed);if(t)t.textContent=`${Math.round(d.tyre)}%`;if(m)m.textContent=`${Math.round(d.engineTemp)}°`;if(e)e.textContent=`${Math.round(d.energy)}%`}
    for(const d of sim.drivers){const car=root.querySelector(`[data-car="${d.id}"]`);if(!car||d.eliminated&&isQualifyingSession()){if(car)car.style.opacity=".15";continue}const point=path?.getPointAtLength(((d.progress%1)+1)%1*pathLength);if(point)car.setAttribute("transform",`translate(${point.x} ${point.y})`);car.style.opacity=d.retired?".12":d.active||isRaceSession()?"1":".32"}
  }

  function pushEvent(text,radio=null){sim.events.unshift(text);sim.events=sim.events.slice(0,20);const msg=root.querySelector("#race-message");if(msg)msg.textContent=text;if(radio){sim.radio.unshift(radio);sim.radio=sim.radio.slice(0,8)}}
  function setControl(status,duration=0,message=""){sim.raceControl=status;sim.neutralRemaining=duration;if(message)pushEvent(message)}
  function updateWeather(dt){if(rainEvent&&isRaceSession()){const lap=leader()?.progress||0,target=lap>sessionLaps()*.28&&lap<sessionLaps()*.72?72:0;sim.weather.rain+=Math.sign(target-sim.weather.rain)*Math.min(Math.abs(target-sim.weather.rain),dt*1.1)}sim.weather.wet=clamp(sim.weather.wet+(sim.weather.rain>8?dt*.7:-dt*.28));sim.weather.track=clamp(sim.weather.track+(sim.weather.rain>10?-dt*.03:dt*.008),18,48);sim.weather.condition=sim.weather.rain>48?"CHUVA FORTE":sim.weather.rain>8?"CHUVA":sim.weather.wet>18?"PISTA ÚMIDA":"SECO"}
  function setupFit(){const s=career.technical.setup;return clamp(100-Math.abs(s.frontWing-(circuit.aero>78?72:circuit.power>82?38:54))*.3-Math.abs(s.suspension-(circuit.tyre>75?62:48))*.2)}
  const rivalTeamRating=id=>({mercedes:92,ferrari:89,mclaren:87,"red-bull":84,"racing-bulls":73,alpine:72,haas:68,audi:67,williams:66,"aston-martin":63,cadillac:61}[id]||68);
  function practiceTick(dt){for(const d of sim.drivers){if(!d.controlled)d.active=rng(`${d.id}:${sim.practice}:${Math.floor(sim.elapsed/20)}`)>.18;if(!d.active)continue;const teamRating=d.teamId===career.team.id.replace("team-2026-","")?career.team.overall:rivalTeamRating(d.teamId),performance=(d.overall*.58+teamRating*.18+setupFit()*.24)/100,actualLap=circuit.lapSeconds*(1.085-(performance-.7)*.16);d.progress+=dt/actualLap;d.speed=175+performance*145+rng(`${d.id}:${Math.floor(sim.elapsed)}`)*18;d.tyre=clamp(d.tyre-dt/circuit.lapSeconds*(5+circuit.tyre/12));d.tyreTemp+=(COMPOUNDS[d.compound].temp-d.tyreTemp)*dt*.025;d.engineTemp=clamp(86+d.speed/20,80,122);d.energy=clamp(d.energy-dt*.018);if(Math.floor(d.progress)>d.laps){d.laps=Math.floor(d.progress);const time=actualLap*(.99+rng(`${d.id}:fp:${d.laps}`)*.025);d.last=time;d.best=Math.min(d.best??999,time)}}}
  function qualifyingTick(dt){const contenders=sim.drivers.filter(d=>!d.eliminated).slice(0,activeCount());for(const d of contenders){if(!d.controlled)d.active=rng(`${d.id}:${sim.segment}:${Math.floor(sim.elapsed/22)}`)>.12;if(!d.active)continue;const teamRating=d.teamId===career.team.id.replace("team-2026-","")?career.team.overall:rivalTeamRating(d.teamId),performance=(d.overall*.68+teamRating*.22+setupFit()*.10)/100,actualLap=circuit.lapSeconds*(1.045-(performance-.7)*.13);d.progress+=dt/actualLap;d.speed=205+performance*128;d.tyre=clamp(d.tyre-dt/circuit.lapSeconds*9);if(Math.floor(d.progress)>d.laps){d.laps=Math.floor(d.progress);const time=actualLap*(.992+rng(`${d.id}:${sim.segment}:${d.laps}`)*.018);d.best=Math.min(d.best??999,time)}}}
  function compoundGrip(d){const wet=sim.weather.wet,c=COMPOUNDS[d.compound]||COMPOUNDS.MÉDIO;if(wet>55)return c.wet;if(wet>18)return d.compound==="INTERMEDIÁRIO"?1.03:d.compound==="CHUVA"?.94:c.dry*(1-wet/180);return c.dry}
  function chooseIncidentDriver(seed){const eligible=sim.drivers.filter(d=>!d.retired&&!d.inPit);return eligible[Math.floor(rng(seed)*eligible.length)]}
  function maybeRaceEvent(){
    if(sim.elapsed<sim.nextEventAt||sim.raceControl!=="GREEN")return;const index=sim.eventIndex++,roll=rng(`${career.saveId}:${circuit.id}:${sim.phase}:event:${index}`),lap=Math.floor(leader()?.progress||0)+1;sim.nextEventAt+=220+Math.round(rng(`${circuit.id}:spacing:${index}`)*160);
    if(roll<.07&&sim.stats.redFlags<1){sim.stats.redFlags++;setControl("RED",55,`🔴 Bandeira vermelha na volta ${lap}. Sessão interrompida; relógio e carros neutralizados.`);return}
    if(roll<.16&&sim.stats.safetyCars<2){sim.stats.safetyCars++;setControl("SC",110,"SC Safety Car na pista. Pelotão deve reduzir e não pode ultrapassar.");return}
    if(roll<.27&&sim.stats.virtualSafetyCars<2){sim.stats.virtualSafetyCars++;setControl("VSC",70,"VSC acionado. Todos devem respeitar o delta mínimo.");return}
    if(roll<.39){setControl("YELLOW",28,`🟡 Bandeira amarela no setor ${1+index%3}. Ultrapassagens proibidas.`);return}
    if(roll<.49){const d=chooseIncidentDriver(`limits:${index}`);if(!d)return;d.trackWarnings++;setControl("BLACK_WHITE",18,`◩ Bandeira preta e branca para ${d.name}: limites de pista (${d.trackWarnings}/3).`);if(d.trackWarnings>=3){d.penalty+=5;sim.stats.penalties++;pushEvent(`${d.name} recebe +5s por reincidência nos limites de pista.`)}return}
    if(roll<.55&&sim.stats.retirements<4){const d=chooseIncidentDriver(`retirement:${index}`);if(!d)return;d.retired=true;d.status=rng(`cause:${index}`)>.5?"DNF · FALHA MECÂNICA":"DNF · ACIDENTE";d.speed=0;sim.stats.retirements++;setControl(roll<.525?"VSC":"YELLOW",roll<.525?65:32,`${d.name} abandona: ${d.status.replace("DNF · ","").toLowerCase()}.`);return}
    const selectedDriver=sim.drivers.find(d=>d.controlled&&!d.retired);if(selectedDriver){const messages=["Ritmo estável. Cuide da temperatura dos pneus.","Janela de boxes atualizada conforme o tráfego.","Use o ERS na reta principal; DRS disponível se ficar a menos de um segundo.",rainEvent?"Chuva no radar. Prepare intermediários.":"Condições estáveis até a bandeirada."];pushEvent(`Rádio: ${messages[index%messages.length]}`,{sender:"Lara",text:messages[index%messages.length],priority:index%3===0?"urgent":"normal"})}
  }
  function updateControl(dt){if(!sim.neutralRemaining)return;sim.neutralRemaining-=dt;if(sim.neutralRemaining<=0){sim.neutralRemaining=0;setControl("GREEN",0,"🟢 Pista liberada. Bandeira verde e ultrapassagens autorizadas.")}}
  function finishPit(d){const p=d.pit;d.inPit=false;d.tyre=100;d.compound=d.targetCompound;d.usedCompounds.push(d.compound);d.pitCooldown=1;d.totalPitTime+=p.total;d.pitHistory.push({...p,lap:d.lastPitLap,compound:d.compound});d.lastPitService=p.service;d.pit=null;d.pitRemaining=0;const nextFraction=(d.pitStops+1)/(d.plannedStops+1);d.pitLap=Math.max(Math.floor(d.progress)+2,Math.round(sessionLaps()*nextFraction));pushEvent(`${d.name}: serviço ${p.service.toFixed(2)}s, tempo total de box ${p.total.toFixed(2)}s, pneus ${d.compound.toLowerCase()}.`,d.controlled?{sender:"Diego",text:`Parada concluída em ${p.service.toFixed(2)}s; perda total ${p.total.toFixed(2)}s.`,priority:"normal"}:null)}
  function raceTick(dt){
    updateWeather(dt);updateControl(dt);maybeRaceEvent();const neutralFactor=sim.raceControl==="RED"?0:sim.raceControl==="SC"?.48:sim.raceControl==="VSC"?.62:sim.raceControl==="YELLOW"?.78:1;
    for(const d of sim.drivers){
      if(d.retired){d.speed=0;continue}d.active=true;let driveDt=dt;
      if(d.inPit){const consumed=Math.min(driveDt,d.pitRemaining);d.pitRemaining-=consumed;d.pit.elapsed+=consumed;driveDt-=consumed;d.speed=d.pit.elapsed<d.pit.entry?80:d.pit.elapsed<d.pit.entry+d.pit.service?0:80;if(d.pitRemaining<=.001)finishPit(d);if(driveDt<=0)continue}
      if(neutralFactor===0){d.speed=0;continue}
      const controlled=d.controlled,paceBoost=controlled?(d.paceMode==="attack"?.035:d.paceMode==="conserve"?-.028:0):(rng(`${d.id}:mode:${Math.floor(sim.elapsed/40)}`)-.5)*.025,engineBoost=controlled?(d.engineMode==="push"?.022:d.engineMode==="conserve"?-.02:0):0,ersBoost=d.ersMode==="deploy"&&d.ers>5?.018:d.ersMode==="harvest"?-.012:0,teamRating=d.teamId===career.team.id.replace("team-2026-","")?career.team.overall:rivalTeamRating(d.teamId),tyreLife=clamp(.72+d.tyre/360,.70,1),damageFactor=1-d.damage/260,base=.88+(d.overall*.62+teamRating*.38-70)/500;
      const ahead=order().filter(x=>!x.retired&&x!==d&&adjustedProgress(x)>adjustedProgress(d)).at(-1),gap=ahead?(adjustedProgress(ahead)-adjustedProgress(d))*circuit.lapSeconds:99;d.drs=sim.raceControl==="GREEN"&&d.progress>2&&gap<=1;const traffic=gap<.65&&!d.drs?.988:1,drsBoost=d.drs?.014:0;
      const step=driveDt/circuit.lapSeconds*base*(1+paceBoost+engineBoost+ersBoost+drsBoost)*tyreLife*compoundGrip(d)*damageFactor*neutralFactor*traffic;d.progress+=step;d.speed=(190+base*115+(paceBoost+engineBoost+ersBoost+drsBoost)*180)*neutralFactor;
      const wearPerLap=(8+circuit.tyre/11)*(COMPOUNDS[d.compound]?.wear||1)*(paceBoost>0?1.22:paceBoost<0?.82:1);d.tyre=clamp(d.tyre-step*wearPerLap);d.tyreTemp+=(COMPOUNDS[d.compound].temp+(paceBoost>0?7:0)-d.tyreTemp)*driveDt*.04;d.engineTemp=clamp(d.engineTemp+driveDt*((engineBoost>.01?.11:-.025)+(d.engineTemp<99?.025:0)),82,132);d.fuel=clamp(d.fuel-step*(100/sessionLaps())*(d.engineMode==="push"?1.08:d.engineMode==="conserve"?.94:1));d.ers=clamp(d.ers+driveDt*(d.ersMode==="harvest"?.28:d.ersMode==="deploy"?-.42:.04));d.energy=d.ers;
      const lap=Math.floor(d.progress);if(lap>d.laps){d.laps=lap;if(d.pitCooldown>0)d.pitCooldown--}const scheduled=d.pitStops<d.plannedStops&&lap>=d.pitLap,emergency=d.tyre<19||d.fuel<2||d.damage>55;if(!d.inPit&&d.pitCooldown===0&&(scheduled||emergency)&&lap<sessionLaps()-1)startPit(d,false);if(sim.weather.wet>35&&!["INTERMEDIÁRIO","CHUVA"].includes(d.compound)&&!d.inPit&&d.pitCooldown===0){d.targetCompound=sim.weather.wet>62?"CHUVA":"INTERMEDIÁRIO";startPit(d,false)}if(d.tyre<8)d.progress-=driveDt/circuit.lapSeconds*.22;if(d.engineTemp>124){d.progress-=driveDt/circuit.lapSeconds*.12;d.damage=clamp(d.damage+driveDt*.012)}if(d.fuel<=0)d.progress-=driveDt/circuit.lapSeconds*.45;
    }
    const lead=leader();if(lead&&lead.progress>=sessionLaps())sim.phase==="sprint"?finishSprint():finishRace();
  }
  function tick(now){const raw=Math.min(.08,(now-sim.lastFrame)/1000);sim.lastFrame=now;if(sim.running&&!sim.finished){const dt=raw*(qa?3000:simulationSpeedMultiplier(sim.speed));sim.elapsed+=dt;if(sim.phase==="practice")practiceTick(dt);if(isQualifyingSession())qualifyingTick(dt);if(isRaceSession())raceTick(dt);if(!isRaceSession()&&sim.elapsed>=sim.duration&&!sim.finished)finishSession();paint()}raf=requestAnimationFrame(tick)}

  function ensureAiLapTimes(){
    if(sim.phase!=="practice"&&!isQualifyingSession())return;
    const eligible=isQualifyingSession()?sim.drivers.filter(d=>!d.eliminated).slice(0,activeCount()):sim.drivers;
    for(const d of eligible){
      if(d.controlled||d.best)continue;
      const teamRating=d.teamId===career.team.id.replace("team-2026-","")?career.team.overall:rivalTeamRating(d.teamId);
      const performance=isQualifyingSession()?(d.overall*.68+teamRating*.22+setupFit()*.10)/100:(d.overall*.58+teamRating*.18+setupFit()*.24)/100;
      const base=isQualifyingSession()?circuit.lapSeconds*(1.045-(performance-.7)*.13):circuit.lapSeconds*(1.085-(performance-.7)*.16);
      d.best=base*(.993+rng(`${d.id}:${sim.segment}:fallback`)*.017);
    }
  }
  function finishSession(){sim.running=false;sim.finished=true;sim.elapsed=sim.duration;ensureAiLapTimes();if(sim.phase==="practice")finishPractice();else if(isQualifyingSession())finishQualifying();else if(sim.phase==="sprint")finishSprint();else if(sim.phase==="race")finishRace()}
  function finishPractice(){const sorted=order();career.technical.weekend.practiceRuns.push({session:`TL${sim.practice}`,pace:Math.round(100-(sorted[0]?.best||80)),setup:Math.round(Object.values(career.technical.setup).reduce((a,b)=>a+b,0)/4),tyreWear:Math.round(100-(selected()?.tyre||100))});career.technical.weekend.telemetry={pace:Math.round(100-(selected()?.best||80)),setup:Math.round(Object.values(career.technical.setup).reduce((a,b)=>a+b,0)/4),tyreWear:Math.round(100-(selected()?.tyre||100)),confidence:68+sim.practice*8};const button=circuit.sprint?"AVANÇAR PARA CLASSIFICAÇÃO SPRINT":sim.practice<3?`AVANÇAR PARA TL${sim.practice+1}`:"AVANÇAR PARA CLASSIFICAÇÃO";showSummary(`TL${sim.practice} CONCLUÍDO`,sorted.slice(0,10),button);persist(`TL${sim.practice} concluído em ${circuit.name}.`)}
  function finishQualifying(){const sorted=order().filter(d=>!d.eliminated);if(sim.phase==="sprint-qualifying"){const grid=sorted.slice();grid.forEach((d,i)=>d.position=i+1);sim.sprintGrid=grid;showSummary("GRID DA SPRINT DEFINIDO",grid.slice(0,10),"INICIAR SPRINT");persist(`Grid da Sprint definido para ${circuit.name}.`);return}if(sim.segment==="Q1"){const out=sorted.slice(16);out.forEach(d=>d.eliminated=true);sim.q1Out=out;showSummary("Q1 CONCLUÍDO",sorted.slice(0,16),"AVANÇAR PARA Q2")}else if(sim.segment==="Q2"){const out=sorted.slice(10);out.forEach(d=>d.eliminated=true);sim.q2Out=out;showSummary("Q2 CONCLUÍDO",sorted.slice(0,10),"AVANÇAR PARA Q3")}else{const top=sorted.slice(0,10),grid=[...top,...sim.q2Out,...sim.q1Out];grid.forEach((d,i)=>d.position=i+1);sim.grid=grid;career.technical.weekend.qualifying=grid.map(d=>({driverId:d.id,name:d.name,teamId:d.teamId,position:d.position,bestLap:d.best}));career.technical.weekend.phase="grid-set";showSummary("GRID DE LARGADA DEFINIDO",grid.slice(0,10),"INICIAR CORRIDA");persist(`Grid completo definido para ${circuit.name}.`)}}
  function showSummary(title,drivers,button){const box=root.querySelector("#session-summary");if(!box)return;box.hidden=false;box.innerHTML=`<div class="summary-card"><p class="eyebrow">RESULTADO OFICIAL</p><h2>${title}</h2><div class="summary-results">${drivers.slice(0,10).map((d,i)=>`<span><b>P${i+1}</b><i style="--team:${d.team.color}"></i>${flagHtml(d.name)} ${d.name}<small>${isRaceSession()?gapText(d,drivers[0]):d.best?lapTime(d.best):"—"}</small></span>`).join("")}</div><button class="pit-primary" data-live="next-session">${button}</button></div>`}
  function resetDrivers(keepGrid=false){for(const [i,d] of sim.drivers.entries()){d.active=false;d.best=null;d.last=null;d.tyre=100;d.tyreTemp=88;d.energy=100;d.ers=100;d.engineTemp=92;d.speed=0;d.laps=0;d.inPit=false;d.eliminated=keepGrid?d.eliminated:false;if(!keepGrid)d.progress=(22-i)*.002}}
  function nextSession(){const box=root.querySelector("#session-summary");if(box)box.hidden=true;sim.finished=false;sim.elapsed=0;sim.running=false;if(sim.phase==="practice"&&circuit.sprint){sim.phase="sprint-qualifying";sim.segment="SQ";sim.duration=durationFor("SQ");resetDrivers()}else if(sim.phase==="practice"&&sim.practice<3){sim.practice++;sim.segment=`TL${sim.practice}`;sim.duration=durationFor(sim.segment);resetDrivers()}else if(sim.phase==="practice"||sim.phase==="sprint"){sim.phase="qualifying";sim.segment="Q1";sim.duration=durationFor("Q1");sim.q1Out=[];sim.q2Out=[];resetDrivers()}else if(sim.phase==="sprint-qualifying"){startRaceLike("sprint");return}else if(sim.phase==="qualifying"&&sim.segment==="Q1"){sim.segment="Q2";sim.duration=durationFor("Q2");resetDrivers(true)}else if(sim.phase==="qualifying"&&sim.segment==="Q2"){sim.segment="Q3";sim.duration=durationFor("Q3");resetDrivers(true)}else if(sim.phase==="qualifying"){startRaceLike("race");return}render()}
  function startRaceLike(type){sim.phase=type;sim.segment=type==="sprint"?"SPRINT":"RACE";sim.duration=circuit.lapSeconds*sessionLaps();sim.elapsed=0;sim.finished=false;sim.running=false;sim.raceStarted=true;sim.eventIndex=0;sim.nextEventAt=240;sim.raceControl="GREEN";sim.neutralRemaining=0;const grid=(type==="sprint"?sim.sprintGrid:sim.grid)||order();sim.drivers=grid.map((d,i)=>{const compound=i<10?"MACIO":"MÉDIO",planned=type==="sprint"?0:(circuit.tyre>82?2:1),firstPit=Math.max(5,Math.round(sessionLaps()/(planned+1))+(i%5)-2);return{...d,eliminated:false,active:true,progress:(grid.length-i)*.003,position:i+1,best:null,last:null,tyre:100,tyreTemp:82,compound,startCompound:compound,usedCompounds:[compound],pitStops:0,plannedStops:planned,pitHistory:[],pit:null,pitRemaining:0,pitCooldown:0,lastPitLap:-20,totalPitTime:0,lastPitService:null,engineTemp:91,energy:100,ers:100,fuel:100,damage:0,trackWarnings:0,penalty:0,status:"RUNNING",retired:false,drs:false,pitLap:firstPit,targetCompound:compound==="MACIO"?"MÉDIO":"DURO",inPit:false}});pushEvent(type==="sprint"?"Luzes apagadas: Sprint iniciada. Não há parada obrigatória.":"Formação concluída. Em pista seca, todos devem usar dois compostos e realizar ao menos uma parada.");render()}
  function startPit(d,manual=true){const lap=Math.floor(d.progress);if(d.inPit||d.retired)return false;if(d.pitCooldown>0||lap===d.lastPitLap){if(manual)pushEvent(`${d.name}: chamada aos boxes recusada; aguarde completar outra volta.`);return false}if(lap>=sessionLaps()-1){if(manual)pushEvent(`${d.name}: janela de boxes encerrada.`);return false}if(sim.weather.wet<18&&d.pitStops===0&&d.targetCompound===d.startCompound)d.targetCompound=d.startCompound==="MACIO"?"MÉDIO":"DURO";const ops=career.team.staff.filter(x=>x.department==="Operações"||x.department==="Corrida"),crew=d.controlled?Math.round(ops.reduce((a,x)=>a+x.rating,0)/Math.max(1,ops.length)):72,{entry,service,exit,total}=calculatePitTiming({pitLoss:circuit.pitLoss||22,teamId:d.teamId,crew,seed:`${d.id}:pit:${d.pitStops}:${lap}`});d.inPit=true;d.pitStops++;d.lastPitLap=lap;d.lastPitService=service;d.pit={entry,service,exit,total,elapsed:0};d.pitRemaining=total;pushEvent(`${d.name} entra nos boxes: entrada ${entry.toFixed(1)}s + serviço ${service.toFixed(2)}s + saída ${exit.toFixed(1)}s = ${total.toFixed(2)}s.`);return true}
  function raceRows(){const dry=sim.weather.wet<18;for(const d of sim.drivers)if(sim.phase==="race"&&dry&&d.pitStops===0&&!d.retired){d.penalty+=20;sim.stats.penalties++;pushEvent(`${d.name}: +20s por não cumprir a parada obrigatória.`)}const result=order();result.forEach((d,i)=>d.position=i+1);return result.map((d,i)=>({driverId:d.id,name:d.name,teamId:d.teamId,teamName:d.team.name,flag:NATIONALITY[d.name]?COUNTRY_LABEL[NATIONALITY[d.name]]:"FIA",position:i+1,compound:d.compound,tyre:Math.round(d.tyre),pitStops:d.pitStops,pitService:d.lastPitService,totalPitTime:Number(d.totalPitTime.toFixed(2)),penalty:d.penalty,status:d.retired?"DNF":"FINISHED",reason:d.retired?d.status:null,ruleCompliant:sim.phase==="sprint"||!dry||d.pitStops>0,gap:i===0?0:Number(Math.max(0,(adjustedProgress(result[0])-adjustedProgress(d))*circuit.lapSeconds).toFixed(3))}))}
  function finishSprint(){if(sim.finished)return;sim.running=false;sim.finished=true;sim.raceControl="CHEQUERED";const rows=raceRows(),saved=recordSprintResult(career,rows,{...sim.stats});if(saved.ok)career=saved.state;persist(saved.reason);showSummary("SPRINT CONCLUÍDA",order().slice(0,10),"AVANÇAR PARA CLASSIFICAÇÃO")}
  function finishRace(){if(sim.finished&&sim.phase==="podium")return;sim.running=false;sim.finished=true;sim.raceControl="CHEQUERED";pushEvent("🏁 Bandeira quadriculada. Resultado provisório sujeito às penalidades.");const rows=raceRows(),saved=recordRaceResult(career,rows,{...sim.stats});if(saved.ok)career=saved.state;persist(saved.reason);sim.phase="podium";renderPodium(order())}
  function renderPodium(result){cancelAnimationFrame(raf);root.innerHTML=`<section class="podium-screen"><div class="confetti-layer"></div><button class="broadcast-exit" data-live="exit">SAIR E SALVAR</button><p class="eyebrow">${circuit.flag} ${circuit.grandPrix.toUpperCase()}</p><h1>PÓDIO</h1><div class="podium-stage"><article class="podium-place second"><span>🥈</span><img src="assets/official/driver-${slug(result[1].name)}.webp" alt="${result[1].name}"><h2>${flagHtml(result[1].name)} ${result[1].name}</h2><b>${result[1].team.name}</b><i>2</i></article><article class="podium-place first"><span>🏆</span><img src="assets/official/driver-${slug(result[0].name)}.webp" alt="${result[0].name}"><h2>${flagHtml(result[0].name)} ${result[0].name}</h2><b>${result[0].team.name}</b><i>1</i></article><article class="podium-place third"><span>🥉</span><img src="assets/official/driver-${slug(result[2].name)}.webp" alt="${result[2].name}"><h2>${flagHtml(result[2].name)} ${result[2].name}</h2><b>${result[2].team.name}</b><i>3</i></article></div><div class="podium-actions"><button class="pit-primary" data-live="exit">VOLTAR AO PADDOCK</button></div></section>`;root.onclick=handleClick}
  function persist(message){career.updatedAt=new Date().toISOString();callbacks.onSave?.(clone(career),message)}
  function exitLive(){cancelAnimationFrame(raf);persist("Fim de semana salvo.");root.hidden=true;root.innerHTML="";callbacks.onExit?.(clone(career))}
  function handleInput(e){const d=selected();if(e.target.dataset.setup){career.technical.setup[e.target.dataset.setup]=Number(e.target.value);e.target.previousElementSibling.querySelector("b").textContent=e.target.value;persist("Acerto atualizado durante a sessão.")}if(e.target.dataset.strategy){d[e.target.dataset.strategy]=e.target.type==="number"?Number(e.target.value):e.target.dataset.strategy==="plannedStops"?Number(e.target.value):e.target.value}}
  function handleClick(e){const b=e.target.closest("[data-live]");if(!b)return;const action=b.dataset.live;if(action==="exit")exitLive();if(action==="speed"){sim.speed=Number(b.dataset.value);root.querySelectorAll('[data-live="speed"]').forEach(x=>x.classList.toggle("is-active",x===b))}if(action==="pause"){sim.running=!sim.running;b.textContent=sim.running?"PAUSAR":"CONTINUAR"}if(action==="select-driver"){sim.selectedId=b.dataset.id;root.querySelectorAll('[data-live="select-driver"]').forEach(x=>x.classList.toggle("is-active",x.dataset.id===sim.selectedId));const p=root.querySelector("#telemetry-panel");if(p)p.innerHTML=telemetryHtml()}if(action==="toggle-track"){const d=selected();d.active=!d.active;b.textContent=d.active?"RECOLHER AOS BOXES":"ENVIAR PARA A PISTA"}if(action==="next-session")nextSession();if(action==="pit")startPit(selected(),true)}
  render();raf=requestAnimationFrame(tick);return{destroy(){cancelAnimationFrame(raf);root.hidden=true;root.innerHTML=""}};
}
